### ISSUE TITLE
load_pytorch 函数中发生错误

### ISSUE THREAD

**Issue by stanley40606** [rockchip-linux/rknn-toolkit#103]
Environment:pytorch1.5.1,rknntoolkit1.7.0
E Catch exception when loading pytorch model: postprocess_jit.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 155, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2910, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2718, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.report_missing_conversion
E NotImplementedError: The following operators are not implemented: ['aten::expand', 'aten::_cast_Float', 'aten::_cast_Long', 'aten::__getitem__', 'aten::ge', 'aten::gt', 'aten::gt_', 'aten::sort', 'aten::clamp', 'prim::device', 'aten::index', 'aten::max', 'prim::dtype', 'aten::sub_', 'aten::copy_', 'aten::lt', 'aten::min']

**Comment by stanley40606** [comment]
pytorch model construct in pytorch=1.6.0 still have error

E Model file postprocess_jit_torch16 not exists!
>>> model = 'postprocess_jit_torch16.pt'
>>> ret = rknn.load_pytorch(model=model, input_size_list=input_size_list)
postprocess_jit_torch16.pt ********************
E Catch exception when loading pytorch model: postprocess_jit_torch16.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 155, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2910, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2718, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.report_missing_conversion
E NotImplementedError: The following operators are not implemented: ['aten::clamp', 'prim::device', 'aten::expand', 'aten::sub_', 'aten::gt_', 'aten::sort', 'aten::index', 'aten::__getitem__', 'aten::ge', 'aten::min', 'aten::lt', 'aten::max', 'prim::dtype', 'aten::gt', 'aten::copy_']
