### ISSUE TITLE
pytorch模型转换问题

### ISSUE THREAD

**Issue by wujialiang** [rockchip-linux/rknn-toolkit#11]
使用rknn-toolkit-v1.3.0\examples\pytorch例子转换pytorch模型失败，具体日志如下：

root@169b24048060:/examples/pytorch/resnet18# python test.py 
--> config model
done
--> Loading model
/usr/local/lib/python3.5/dist-packages/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release.. Use node.outputs instead.
  warnings.warn(message)
./resnet18.pt ********************
WARNING: Token 'COMMENT' defined, but not used
WARNING: There is 1 unused token
Syntax error in input! LexToken(NAMED_IDENTIFIER,'None',5,263)
done
--> Building model
W Genreate input meta fail, please check model.
W External input meta file "/tmp/tmp6iu3la8h/resnet18_inputmeta.yml" is not exists.
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    ret = rknn.build(do_quantization=True, dataset='./dataset.txt')
  File "/usr/local/lib/python3.5/dist-packages/rknn/api/rknn.py", line 238, in build
    ret = self.rknn_base.build(do_quantization=do_quantization, dataset=dataset, pack_vdata=pre_compile, batch_size=rknn_batch_size)
  File "rknn/api/rknn_base.py", line 719, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/rknn_base.py", line 2249, in rknn.api.rknn_base.RKNNBase._generate_inputmeta
IndexError: list index out of range

请问是什么问题?谢谢

**Comment by Gug3** [comment]
请问你这边解决了吗？我今天也遇到了这个问题。。。 如果解决了能否告知一下是什么原因

**Comment by poirotZhu** [comment]
I also met this problem. I found that you can not set the stride parameter in nn.conv2d as an int. You should use tuple, such as (1,1). Hope this can solve you problem.
