### ISSUE TITLE
loading onnx model

### ISSUE THREAD

**Issue by 13718413797** [rockchip-linux/rknn-toolkit#114]
D Calc tensor Reshape_844 (1, 1, 270, 480)
E Calc node ScatterND : ScatterND_397 output shape fail
W ----------------Warning(2)----------------
E Catch exception when loading onnx model: model.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/scatter_nd.py", line 28, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.scatter_nd.ScatterND
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/scatter_nd.py", line 21, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.scatter_nd.scatter_nd_impl
E IndexError: arrays used as indices must be of integer (or boolean) type
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 292, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 94, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 984, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/api/rknn_log.py", line 312, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node ScatterND : ScatterND_397 output shape fail

**Comment by zen-xingle** [comment]
ScatterND is not support now.
You can check all the op supported here.https://github.com/rockchip-linux/rknn-toolkit/blob/master/doc/RKNN_OP_Support_V1.7.0.md
