### ISSUE TITLE
E [op_check:180]Inputs/Outputs data type not support:  UINT8, ASYM UINT8, ASYM INT32, ASYM UINT8 E [setup_node:456]Check node[30] CONV2D fail

### ISSUE THREAD

**Issue by MrOCW** [rockchip-linux/rknn-toolkit#119]
Hi,

I exported YOLOv5s to ONNX to RKNN but I am getting this error:

```
--> Init runtime environment
librknn_runtime version 1.7.0 (9ad5c07 build: 2021-08-06 15:20:31 base: 1131)
E [op_check:180]Inputs/Outputs data type not support:  UINT8, ASYM UINT8, ASYM INT32, ASYM UINT8
E [setup_node:456]Check node[30] CONV2D fail
Create rknn graph fail!
Create RKNN model fail, error=-6
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 884, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID
```

This is the model with the first Conv2D node selected in Netron
![image](https://user-images.githubusercontent.com/67644448/139586930-1c45bf94-38db-4957-8a4f-199659e5b960.png)

**Comment by zen-xingle** [comment]
Is your ONNX model already quantized (by onnxruntime etc.)?

For the float yolov5s onnx model exported from https://github.com/ultralytics/yolov5, we couldn't reproduce this bug. It's appreciated if your can upload your yolov5s onnx model, then we can check out how this bug arise.

**Comment by MrOCW** [comment]
@zen-xingle yes it has been quantized in ONNX. https://github.com/neuralmagic/sparseml/tree/main/integrations/ultralytics-yolov5 was used for Quantization Aware Training. This is the onnx model produced
https://drive.google.com/file/d/1v7AW48fpXKXR32VUTZTYLL5jlZALGB5-/view?usp=sharing
