### ISSUE TITLE
tensorflow量化感知训练，加载成功build失败

### ISSUE THREAD

**Issue by SmartSmallBoy** [rockchip-linux/rknn-toolkit#135]
I Start T2C Switcher...
D Optimizing network with broadcast_op, t2c_fc
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/switcher/mode_switcher.py", line 353, in rknn.base.RKNNlib.switcher.mode_switcher.ModeSwitcher.build_mark
E   File "rknn/base/RKNNlib/switcher/mode_switcher.py", line 195, in rknn.base.RKNNlib.switcher.mode_switcher.ModeSwitcher.optimize_mark
E   File "rknn/base/RKNNlib/switcher/mark_optimize.py", line 656, in rknn.base.RKNNlib.switcher.mark_optimize.MarkOptimize.apply
E   File "rknn/base/RKNNlib/switcher/mark_optimize.py", line 652, in rknn.base.RKNNlib.switcher.mark_optimize.MarkOptimize.forward_mark
E   File "rknn/base/RKNNlib/switcher/mark_optimize.py", line 28, in rknn.base.RKNNlib.switcher.mark_optimize.fwd_upstream
E AttributeError: 'NoneType' object has no attribute 'reset_shape_format'
E Please feedback the detailed log file <log.txt> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by SmartSmallBoy** [comment]
> [``](url)
