### ISSUE TITLE
tensorflow lite量化感知训练模型转换成功，build成功，导出成功，init_runtime()失败 Inputs/Outputs data type not support: ASYM UINT8,  INT8,  INT32, ASYM UINT8

### ISSUE THREAD

**Issue by SmartSmallBoy** [rockchip-linux/rknn-toolkit#136]
D [validate_op_io_types:165]Validate [PERMUTE]
D [print_tensor:146]in(0) : id[ 326] vtl[1] const[0] shape[ 3, 640, 640, 1   ] fmt[u8 ] qnt[ASM zp=115, scale=1.077416]
D [print_tensor:146]out(0): id[ 160] vtl[1] const[0] shape[ 640, 640, 3, 1   ] fmt[u8 ] qnt[ASM zp=115, scale=1.077416]
D [setup_node:441]Setup node id[24] uid[2] op[CONV2D] name[model/quant_conv1/Conv2D1_2]
D [validate_op_io_types:165]Validate [CONV2D]
E [op_check:180]Inputs/Outputs data type not support: ASYM UINT8,  INT8,  INT32, ASYM UINT8
E [setup_node:456]Check node[24] CONV2D fail
Create rknn graph fail!
I [remove_client_ops:5532]remove_client_ops num=0
I [remove_client_ops:5543]remove_client_ops finish
Create RKNN model fail, error=-6
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 897, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID
E Please feedback the detailed log file <log.txt> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
-1

**Comment by SmartSmallBoy** [comment]
![image](https://user-images.githubusercontent.com/82008372/143764535-9f15427c-9d7e-42c7-9ed5-5638d554c5df.png)这是出错的rknn模型节点截图

**Comment by zen-xingle** [comment]
RKNN目前支持权重保存为 uint8 的 tflite量化模型。这是以前他们默认采取uint8保存的，他们最近好像修改成默认用 int8格式保存权重了。

**Comment by SmartSmallBoy** [comment]
> RKNN目前支持权重保存为 uint8 的 tflite量化模型。这是以前他们默认采取uint8保存的，他们最近好像修改成默认用 int8格式保存权重了。

那这个怎么解决呢，我看了下tflite官方的说明，是uint8变成int8了，但是计算公式是没变的，还是(data-zero_point)*scale，这个可以兼容一下吗

**Comment by zen-xingle** [comment]
我们评估下，兼容的话也会是下个版本的功能，如果你项目比较急，推荐看下怎么设置成uint8做量化。
