### ISSUE TITLE
quantization mxnet model error

### ISSUE THREAD

**Issue by Harry-Hu** [rockchip-linux/rknn-toolkit#142]
[cov2.zip](https://github.com/rockchip-linux/rknn-toolkit/files/7650754/cov2.zip)

HI RK :

    When quantization mxnet model(attach files),have a error as follow(if not quantization,it build OK) :

     ease use tf.compat.v1.image.resize_nearest_neighbor instead.

D Real output shape: (1, 14, 14, 64)
D Process crop0_131 ...
D RKNN output shape(slice): (1 14 14 0)
D Tensor @crop0_131:out0 type: float32
D Real output shape: (1, 14, 14, 0)
D Process rknn__plus0_132 ...
D RKNN output shape(eltwise): (1 14 14 64)
D Tensor @rknn__plus0_132:out0 type: asymmetric_affine
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "/media/harry/043c6f5d-07ac-425d-9a58-3ee96fab9ce3/work/virtualenv/rv1109_npu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
E     c_op = c_api.TF_FinishOperation(op_desc)
E tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 3 in both shapes must be equal, but are 64 and 0. Shapes are [1,14,14,64] and [1,14,14,0].
E 	From merging shape 0 with other shapes. for 'rknn__plus0_132/rknn__plus0_132' (op: 'AddN') with input shapes: [1,14,14,64], [1,14,14,0].
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "/media/harry/043c6f5d-07ac-425d-9a58-3ee96fab9ce3/work/virtualenv/rv1109_npu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
E     op_def=op_def)
E   File "/media/harry/043c6f5d-07ac-425d-9a58-3ee96fab9ce3/work/virtualenv/rv1109_npu/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
E     return func(*args, **kwargs)
E   File "/media/harry/043c6f5d-07ac-425d-9a58-3ee96fab9ce3/work/virtualenv/rv1109_npu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
E     op_def=op_def)
E   File "/media/harry/043c6f5d-07ac-425d-9a58-3ee96fab9ce3/work/virtualenv/rv1109_npu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
E     control_input_ops)
E   File "/media/harry/043c6f5d-07ac-425d-9a58-3ee96fab9ce3/work/virtualenv/rv1109_npu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
E     raise ValueError(str(e))
E ValueError: Dimension 3 in both shapes must be equal, but are 64 and 0. Shapes are [1,14,14,64] and [1,14,14,0].
E 	From merging shape 0 with other shapes. for 'rknn__plus0_132/rknn__plus0_132' (op: 'AddN') with input shapes: [1,14,14,64], [1,14,14,0].
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Build model failed!

   THX

**Comment by zen-xingle** [comment]
Hi Harry-Hu:
  The error is caused by the "crop" op of the model. The output of "crop", parsed by RKNN-toolkit, is set to be  [1,14,14,0] but not  [1,14,14,64], which leads to the error dimension mismatch for the input of "add" op. 
  We check the official doc on https://mxnet.apache.org/versions/1.6/api/r/docs/api/mx.symbol.Crop.html#value. It's said that the 'Crop' op is deprecated and they advise using 'slice' op instead. Maybe you can try to replace the 'Crop' op with 'Slice' op. Or I think that the 'crop' op in this model can be removed and even not affect the inference result.
