### ISSUE TITLE
[pytorch][Generalized Mean Pooling Layer] is not supported.

### ISSUE THREAD

**Issue by Chihiro** [rockchip-linux/rknn-toolkit#143]
pytorch: 1.6.0
target: rv1126
driver: 1.6.0
api: 1.7.0

**E NotImplementedError: The following operators are not implemented: ['aten::pow', 'aten::reciprocal', 'aten::clamp']**

operation:  torch.clamp torch.pow

`class GeneralizedMeanPooling(nn.Module):

    def __init__(self, norm=3, output_size=(1, 1), eps=1e-6, *args, **kwargs):
        super(GeneralizedMeanPooling, self).__init__()
        assert norm > 0
        self.p = float(norm)
        self.output_size = output_size
        self.eps = eps

    def forward(self, x):
        x = x.clamp(min=self.eps).pow(self.p)
        return F.adaptive_avg_pool2d(x, self.output_size).pow(1. / self.p)

    def __repr__(self):
        return self.__class__.__name__ + '(' \
               + str(self.p) + ', ' \
               + 'output_size=' + str(self.output_size) + ')'`

may i get some supports, please!

**Comment by zen-xingle** [comment]
1.'aten::clamp' will be supported in next version 1.7.2.
   But in your case, I think you can replace it with a nn.ReLU op, is almost the same when your eps is 1e-6.
2.'aten::pow' is already supported in version 1.7.1 I think.
3.'aten::reciprocal' is considered to support, for now you can set like  norm = 1/3, then pow(self.p) instead of pow(1./ self.p).

**Comment by Chihiro** [comment]
@zen-xingle  Thank for your tips.

i write the code as follows:
`class GeneralizedMeanPooling(nn.Module):
    
    def __init__(self, norm=3, output_size=(1, 1), eps=1e-6, *args, **kwargs):
        super(GeneralizedMeanPooling, self).__init__()
        assert norm > 0
        self.p = float(norm)
        self.output_size = output_size
        # self.eps = eps
        # self.relu = nn.ReLU()
        self.magic_p = 1. / self.p  
        self.avg_pool2d = nn.AdaptiveAvgPool2d(output_size)
        

    def forward(self, x):
        # x = self.relu(x)
        x = x.pow(self.p)
        x = self.avg_pool2d(x)
        x = x.pow(self.magic_p)
        return x`

which works 
when i am doing 'normal'  quantized.

### **but if i use the 'mmse' quantized algorithm, and batch > 1,** the pow operation raises an exception. as follows:

--> Building model
MMSE Quant Step 0:  96%|████████████████████████████████████████▎ | 119/124 [00:32<00:01,  3.64it/s]
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "/home/tachikoma/anaconda3/envs/rk/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1626, in _create_c_op
E     c_op = c_api.TF_FinishOperation(op_desc)
**E tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 2048 and 2 for 'pow_at_input.1_173_174/Pow' (op: 'Pow') with input shapes: [2,16,8,2048], [2].**
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "/home/tachikoma/anaconda3/envs/rk/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
E     op_def=op_def)
E   File "/home/tachikoma/anaconda3/envs/rk/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
E     return func(*args, **kwargs)
E   File "/home/tachikoma/anaconda3/envs/rk/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
E     op_def=op_def)
E   File "/home/tachikoma/anaconda3/envs/rk/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1790, in __init__
E     control_input_ops)
E   File "/home/tachikoma/anaconda3/envs/rk/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1629, in _create_c_op
E     raise ValueError(str(e))
**E ValueError: Dimensions must be equal, but are 2048 and 2 for 'pow_at_input.1_173_174/Pow' (op: 'Pow') with input shapes: [2,16,8,2048], [2].**
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Build model failed!

is that a bug?
the input of the first pow is     (n, 2048, 16, 8)
the input of the second pow is (n, 2048, 1, 1)

**Comment by Chihiro** [comment]
When using 'normal' or 'kl'  quantized algorithm, we can do quantized normally. But we get 0. output during the inference time.
[https://chevereto.exc1ted.com/image/9LE](url)
[https://chevereto.exc1ted.com/image/Bqs](url)

**Comment by eRaul** [comment]
Please post the input and output shape information of the pow layer to analyze the problem of mmse quantization failure feedback from the qq group.

**Comment by Chihiro** [comment]
shape before pow: torch.Size([1, 2048, 16, 8])
shape after pow: torch.Size([1, 2048, 16, 8])
@eRaul

**Comment by eRaul** [comment]
> shape before pow: torch.Size([1, 2048, 16, 8]) shape after pow: torch.Size([1, 2048, 16, 8]) @eRaul

Using RKNN Toolkit V1.7.1 can not reproduce the problem you feedback. Which version of the tool are you using?

![1640067901(1)](https://user-images.githubusercontent.com/3354725/146881860-ceb3aae4-43b4-4f7a-9726-1b44895b96da.png)

**Comment by Chihiro** [comment]
RKNN Toolkit V1.7.1  
@eRaul 
could you tell me the input and output size of your experiment?
