### ISSUE TITLE
在3399pro上面转换出错

### ISSUE THREAD

**Issue by wanqieddy** [rockchip-linux/rknn-toolkit#149]
E Catch exception when loading pytorch model: yolov5s.torchscript.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 157, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 122, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 1, in init rknn.base.RKNNlib.converter.convert_pytorch_new
E   File "/home/toybrick/.local/lib/python3.7/site-packages/torch/__init__.py", line 196, in <module>
E     from torch._C import *
E RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by zen-xingle** [comment]
pytorch 版本问题，不推荐在3399pro上进行模型转换，建议在pc端做转换
