### ISSUE TITLE
tflite模型转换出错

### ISSUE THREAD

**Issue by Bonoy0328** [rockchip-linux/rknn-toolkit#151]
config model
loading model
E Catch exception when loading tflite model: movenet_thunder.tflite!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\converter\tflite_loader.py", line 533, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser.parse
E   File "rknn\base\RKNNlib\converter\tflite_loader.py", line 463, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser._build_layers
E   File "rknn\base\RKNNlib\converter\tflite_loader.py", line 298, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser._get_layer_RKNN_op
E   File "rknn\base\RKNNlib\converter\lite\RKNN_map_op.py", line 844, in rknn.base.RKNNlib.converter.lite.RKNN_map_op.RKNNMapOp.map_RKNN_ops
E   File "rknn\base\RKNNlib\converter\lite\RKNN_map_op.py", line 811, in rknn.base.RKNNlib.converter.lite.RKNN_map_op._cast
E AttributeError: 'NoneType' object has no attribute 'InDataType'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
load model failed!

**Comment by zen-xingle** [comment]
Sorry for the bug you meet.

The error log is not enough to figure out where it got failed. If the model could be upload and we can take a close look on it. Thank you.

**Comment by Bonoy0328** [comment]
https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/tflite/int8/4?lite-format=tflite
the model is here, thanks for the reply.

**Comment by BeautyMess** [comment]
You can remove the cast node or simplily set the input node as nodes after cast. The problem was caused by the cast op. I succeed when converting multipose MoveNet on Veliscon platform not RKNN.

你转TFLITE的时候从cast后面的节点作为input，这个问题是因为cast里面的op有不支持的部分。
