### ISSUE TITLE
nanodet-plus的torchscript模型转rknn报错`E AttributeError: 'numpy.ndarray' object has no attribute 'url'`

### ISSUE THREAD

**Issue by lx-r** [rockchip-linux/rknn-toolkit#157]
```
E Catch exception when loading pytorch model: nanodet.torchscript.pt!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3985, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 4156, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3783, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.convert_operators
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2485, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.size
E   File "rknn/base/RKNNlib/RKNNnet.py", line 582, in rknn.base.RKNNlib.RKNNnet.RKNNNet.get_layer_by_out_tensor
E AttributeError: 'numpy.ndarray' object has no attribute 'url'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
```

**Comment by zen-xingle** [comment]
Hello, Could you upload the test model and we can take a close look on how it happen? Thank you.

**Comment by mkwml** [comment]
@lx-r 我也遇到了相同的问题，请问您的问题解决了吗？

**Comment by mkwml** [comment]
尝试了一下几种方案，最后问题解决。
1、升级pytorch到1.9.0和torchvision，再测试，load_pytorch函数可以执行成功，但是后面出现其它错误；
2、使用onnx转换模型，可以转换成功，但是预测结果错误；
3、降低onnx opset版本到10，模型转换成功，结果预测正确。

**Comment by zhaodongyang2016** [comment]
@mkwml 想知道，您转到rknn快了得到了多少的加速呢。手上的项目对延迟的容忍很低，又想通过npu来扩大点尺寸提高准确率。
