### ISSUE TITLE
mediapipe中的tflite转换失败hand_landmark_full.tflite

### ISSUE THREAD

**Issue by zhouyangwen** [rockchip-linux/rknn-toolkit#163]
报错如下：
W Verbose file path is invalid, debug info will not dump to file.
D Using CPPUTILS: True
........................................
...........此处省略...........
........................................
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_handedness/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
D Convert layer logistic
D Convert layer dequantize
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_handflag/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
D Convert layer logistic
D Convert layer dequantize
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_landmarks/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
D Convert layer dequantize
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_world_landmarks/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
E Invalid tensor id(2), tensor(@model_1/model/conv_handedness/BiasAdd/ReadVariableOp/resource_dequantize_90:out0)
E Catch exception when loading tflite model: ./hand_landmark_full.tflite!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/tflite_loader.py", line 535, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser.parse
E   File "rknn/base/RKNNlib/converter/tflite_loader.py", line 506, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser._build_connections
E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 144, in rknn.base.RKNNlib.layer.RKNNlayer.RKNNLayer.add_input
E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 26, in rknn.base.RKNNlib.layer.RKNNlayer.IoStruct.add
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Invalid tensor id(2), tensor(@model_1/model/conv_handedness/BiasAdd/ReadVariableOp/resource_dequantize_90:out0)
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by zhouyangwen** [comment]
模型下载地址：
链接：https://pan.baidu.com/s/1SVKbZUQ_fpiANYQnlUYkYQ 
提取码：j43l 
--来自百度网盘超级会员V8的分享

**Comment by kyn817046** [comment]
老哥，解决了吗？我也遇到这个问题
