### ISSUE TITLE
动态输入问题

### ISSUE THREAD

**Issue by yanni1995** [rockchip-linux/rknn-toolkit#170]
Loading dynamic inputs model is not support, please fix it first
E Catch exception when loading onnx model: FCNqat.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 68, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 73, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Loading dynamic inputs model is not support, please fix it first
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by zen-xingle** [comment]
不支持动态输入，导出onnx模型时需要固定维度大小

**Comment by djdll** [comment]
@zen-xingle 请问现在支持动态输入嘛
