### ISSUE TITLE
analysis报错：no devices/emulators found

### ISSUE THREAD

**Issue by sunyihuan326** [rockchip-linux/rknn-toolkit#171]
![1642578239](https://user-images.githubusercontent.com/19549983/150086153-da846bfa-a624-46aa-a98e-f675f3799c4e.png)
analysis运行时报错
error: no devices/emulators found
E Connect to Device Failure (-1)
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 868, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 171, in rknn.api.rknn_runtime.RKNNRuntime.__init__
E   File "rknn/api/rknn_platform_utils.py", line 318, in rknn.api.rknn_platform_utils.start_ntp_or_adb
E Exception: Init runtime environment failed!

**Comment by zen-xingle** [comment]
你好，

请参考doc/trouble_shooting文档先排查板子的连接问题
