### ISSUE TITLE
量化模型转换rknn时报错

### ISSUE THREAD

**Issue by xingyueye** [rockchip-linux/rknn-toolkit#191]
你好，我在尝试部署一个量化模型（带Q/DQ的onnx模型）时报错如下：
```
Traceback (most recent call last):
  File "rknn_convert.py", line 90, in <module>
    convert_model(model_path, out_path, pre_compile)
  File "rknn_convert.py", line 73, in convert_model
    rknn.build(do_quantization=model['quantize'], dataset=dataset_path)
  File "xxx/rknn/api/rknn.py", line 262, in build
    inputs = self.rknn_base.net.get_input_layers()
AttributeError: 'NoneType' object has no attribute 'get_input_layers'
```
希望能够得到支持

**Comment by zen-xingle** [comment]
你好，
toolkit1目前仅支持onnxruntime1.5.2生成的onnx量化模型，由于onnx量化功能目前不完善，推荐使用pytorch量化后导出为torchscript格式的模型再转rknn，目前pytorch支持到1.9.0（官方最新是1.10）

**Comment by xingyueye** [comment]
你好，我用onnxruntime1.5.2的量化模型和torchscript的量化模型转换rknn都不能成功，我这里 torch版本1.7.1，  rknn版本1.7.1，
torchscript转换时verbose log如下：
```
E Catch exception when loading pytorch model: models/v12/models_pkg/model_script.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 157, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3978, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3770, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.report_missing_conversion
E **NotImplementedError: The following operators are not implemented: ['aten::fake_quantize_per_tensor_affine']**
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

```
为什么会显示torch的量化操作未支持？

**Comment by 2573614483** [comment]
你好，上述问题解决了吗？求解决方法。
