### ISSUE TITLE
Dynamic input shape issue

### ISSUE THREAD

**Issue by lipo5476** [rockchip-linux/rknn-toolkit#193]
Hello Rockchip team,

I'm using rknn-toolkit version 1.7.1 to convert ONNX model to RKNN format.
I'm getting following error when loading the ONNX model, because of dynamic input shape (width and height) but also when batch is dynamic:
`--> Config model
done
--> Loading model
W Detect Input node:data_input is dynamic input, the shape info is [0, 1, 112, 112]
W Use the follow command to see more detail and try to fix the dynamic dim
W python -m rknn.bin.freeze_inshape_for_onnx_model -h
E Loading dynamic inputs model is not support, please fix it first
E Catch exception when loading onnx model: /mnt/c/Users/user/dev/all_models/ONNX/model.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 68, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 73, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Loading dynamic inputs model is not support, please fix it first
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Load model.onnx failed!`

when I try to run `python -m rknn.bin.freeze_inshape_for_onnx_model -h` it fails with an error: 
`/usr/bin/python3: No code object available for rknn.bin.freeze_inshape_for_onnx_model`

Please help to solve this issue
Thanks

**Comment by zen-xingle** [comment]
Hello,

Sorry for the miss of this file, here it is.
[freeze_inshape_for_onnx_model.zip](https://github.com/rockchip-linux/rknn-toolkit/files/8105516/freeze_inshape_for_onnx_model.zip)

**Comment by LMR2018** [comment]
@zen-xingle @lipo5476  你好，这个问题怎么解决啊？[freeze_inshape_for_onnx_model.zip](https://github.com/rockchip-linux/rknn-toolkit/files/8105516/freeze_inshape_for_onnx_model.zip)这个工具 的使用命令是怎样的？
