### ISSUE TITLE
转换pytorch 出错

### ISSUE THREAD

**Issue by LaiZW** [rockchip-linux/rknn-toolkit#195]
D Optimizing network with merge_ximum, qnt_adjust_coef, multiply_transform, add_extra_io, format_input_ops, auto_fill_zero_bias, conv_kernel_transform, twod_op_transform, strip_op, extend_unstack_split, merge_layer, transform_layer, broadcast_op, strip_op, auto_fill_reshape_zero, adjust_output_attrs, insert_dtype_converterI Start T2C Switcher...
D Optimizing network with broadcast_op, t2c_fc
E Catch exception when building RKNN model!
E Traceback (most recent call last): 
E   File "rknn/base/RKNNlib/switcher/mode_switcher.py", line 373, in rknn.base.RKNNlib.switcher.mode_switcher.T2C_Switcher.switch
E   File "rknn/base/RKNNlib/switcher/mode_switcher.py", line 351, in rknn.base.RKNNlib.switcher.mode_switcher.ModeSwitcher.build_mark
E   File "rknn/base/RKNNlib/switcher/mode_switcher.py", line 184, in rknn.base.RKNNlib.switcher.mode_switcher.ModeSwitcher.mark_ops
E   File "rknn/base/RKNNlib/switcher/mark_ops_table.py", line 286, in rknn.base.RKNNlib.switcher.mark_ops_table._mark_4d_t2c
E   File "rknn/base/RKNNlib/switcher/utils.py", line 47, in rknn.base.RKNNlib.switcher.utils.mark_outputs
E AttributeError: 'NoneType' object has no attribute 'get_format'
E Please feedback the detailed log file <rknn.txt> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by zen-xingle** [comment]
您好，

这个问题可能需要模型debug，您那边是否能提供模型供测试呢？

**Comment by LaiZW** [comment]
这个是我这测试的pt文件，基于1.7.1的rknn-toolkit测试的
链接:https://pan.baidu.com/s/1V4PkRVhZYI-1KBJHy2Utiw 
提取码:ddok

**Comment by tangtang666** [comment]
同样的问题

**Comment by Lzw15537131743** [comment]
> 

@LaiZW 您好，解決了吗？我遇到同样的问题了

**Comment by lzwRover321** [comment]
> 这个是我这测试的pt文件，基于1.7.1的rknn-toolkit测试的 链接:https://pan.baidu.com/s/1V4PkRVhZYI-1KBJHy2Utiw 提取码:ddok

您好，我遇到同样的问题，您这个问题解决了吗？

**Comment by lzwRover321** [comment]
> 这个是我这测试的pt文件，基于1.7.1的rknn-toolkit测试的 链接:https://pan.baidu.com/s/1V4PkRVhZYI-1KBJHy2Utiw 提取码:ddok

@LaiZW 您好，遇到同样的问题，您这个问题解决了吗？
