### ISSUE TITLE
关于onnx转换rknn问题

### ISSUE THREAD

**Issue by miyane-ralo** [rockchip-linux/rknn-toolkit#201]
pth>onnx:
    env：pc 、python3.7、onnx=1.6.0、torch=1.8.1
onnx>rknn:
    env：rk3399+rk1808、python3.7、onnx=1.6.0、rknn_toolkit=1.6.0、torch=1.6.0
Related file links：链接：https://pan.baidu.com/s/1C6hSnbGKns4btDjZbIHvgg 提取码：9966 
Problem Description：

--> config model
done
--> Loading model
W Call onnx.optimizer.optimize fail, skip optimize
E Calc node Conv : Conv_0 output shape fail
W ----------------Warning(1)----------------
E Catch exception when loading onnx model: openpose.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 57, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/conv.py", line 49, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.conv.Conv
E   File "/home/linaro/.local/lib/python3.7/site-packages/torch/__init__.py", line 19, in <module>
E     exit(-1)
E   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
E     raise SystemExit(code)
E SystemExit: -1
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 264, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 135, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 111, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 85, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 434, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 62, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/api/rknn_log.py", line 312, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node Conv : Conv_0 output shape fail

**Comment by SouthIO** [comment]
I have encountered the same problem. Have you solved it？

**Comment by sunnythree** [comment]
I have encoutered the same problem too, Have you solved it?

**Comment by MarioCavero** [comment]
rk3399 with the sdk, works only for python2.7 atm it seems, so the conversions for torch might not be available between those different python versions. Idk if that can be the cause of the problem. After a long time debugging, I finally found [this link](https://zhuanlan.zhihu.com/p/561168150) which explains how to properly install opencv for the sdk:

> According to the official website, their chips can accelerate tensorflow. I am heartbroken because their sample programs are all python 2.7.

> The latest examples of tensorflow are all python 3.8

**Comment by zmcljscy** [comment]
I have encountered the same problem. Have you solved it？
