### ISSUE TITLE
torchscript转换rknn模型出错

### ISSUE THREAD

**Issue by PuNeal** [rockchip-linux/rknn-toolkit#203]
问题描述：使用torch.fx接口经过QAT训练，然后转换得到的torchscript模型在转为rknn模型时出错。
报错信息：
```
W Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.9.0+cu102. This may cause the model to fail to load.
E Catch exception when loading pytorch model: tmp_quantized_scripted_quantized.pth!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 157, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3978, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3770, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.report_missing_conversion
E NotImplementedError: The following operators are not implemented: ['prim::device', 'prim::unchecked_cast', 'aten::replication_pad3d', 'aten::IntImplicit', 'aten::dim', 'aten::remainder', 'aten::len', 'aten::__is__', 'aten::empty', 'prim::dtype', 'aten::format', 'prim::layout', 'prim::Uninitialized', 'aten::copy_', 'aten::FloatImplicit', 'aten::eq', 'aten::reflection_pad1d', 'aten::replication_pad2d', 'aten::neg', 'aten::ne', 'aten::ge', 'aten::__getitem__', 'prim::max', 'aten::floordiv', 'aten::replication_pad1d', 'aten::le', 'prim::min', 'aten::gt', 'aten::append']
E Please feedback the detailed log file <verbose_log.txt> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Load Pytorch model failed!
```
环境信息：rknn: 1.7.1 torch: 1.9.0+cu102 
请问该如何解决这个问题？

**Comment by Dreamgang** [comment]
@PuNeal 请问你后来解决了吗，我最近也遇到这个问题

**Comment by Zhao-hangtian** [comment]
请问如何解决的？ @PuNeal
