### ISSUE TITLE
torchscript 模型如图所示, 有size 算子报错,

### ISSUE THREAD

**Issue by hjwangu** [rockchip-linux/rknn-toolkit#204]
rknn模型里应该支持size算子吧
![image](https://user-images.githubusercontent.com/12236033/156919682-0673500b-6d28-46f6-9cb9-5471522aed64.png)
这个看似size属性,报错了,是mmaction2 的torchscript 模型 转rknn,报错了.
有没有好的解决办法?

**Comment by hjwangu** [comment]
报错日志:

 Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.10.0+cpu. This may cause the model to fail to load.
D match input imgs.1
I Parse prim::Constant at 2
I Parse prim::Constant at 3
I Parse prim::Constant at 4
I Parse prim::Constant at 5
I Parse prim::Constant at 6
I Parse prim::Constant at 7
I Parse aten::size at 10
I Parse prim::NumToTensor at other.1
I Parse aten::size at 12
I Parse prim::NumToTensor at 13
I Parse aten::Int at 14
I Parse aten::size at 15
I Parse prim::NumToTensor at 16
I Parse aten::Int at 17
I Parse aten::size at 18
E Catch exception when loading pytorch model: test.pt!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\app\importer\import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 3985, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 4156, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 3783, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.convert_operators
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 2499, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.size
E IndexError: list index out of range
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
