### ISSUE TITLE
tensorflow.dtypes' has no attribute 'int64

### ISSUE THREAD

**Issue by Myspacel** [rockchip-linux/rknn-toolkit#205]
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 616, in rknn.api.rknn_base.RKNNBase.build
E   File "rknn/api/rknn_base.py", line 1523, in rknn.api.rknn_base.RKNNBase._quantize2
E   File "rknn/base/RKNNlib/RK_nn.py", line 570, in rknn.base.RKNNlib.RK_nn.RKnn.quantize
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 145, in rknn.base.RKNNlib.app.medusa.quantization.Quantization.run
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 58, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._run_quantization
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 773, in rknn.base.RKNNlib.app.medusa.workspace.Workspace.sparse_run
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 230, in rknn.base.RKNNlib.app.medusa.workspace.Workspace._run
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 193, in rknn.base.RKNNlib.app.medusa.workspace.Workspace._setup_graph
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 194, in rknn.base.RKNNlib.app.medusa.workspace.Workspace._setup_graph
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 387, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 391, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 427, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 466, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 471, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 293, in rknn.base.RKNNlib.layer.RKNNlayer.RKNNLayer.compute_tensor
E   File "rknn/base/client/argmax.py", line 49, in rknn.base.client.argmax.ArgMax.compute_out_tensor
E AttributeError: module 'tensorflow.dtypes' has no attribute 'int64'

**Comment by GKXKX123456** [comment]
你好，请问你解决这个问他要了吗？

**Comment by GKXKX123456** [comment]
你好，请问你解决这个问题了吗？

**Comment by zen-xingle** [comment]
请升级到1.7.3版本，应该已经修复了
