### ISSUE TITLE
torch的EfficientNet转RK失败，是Identity算子不支持吗？

### ISSUE THREAD

**Issue by MinYounZhang** [rockchip-linux/rknn-toolkit#208]
log如下，查了下OP手册torch没包括Identity算子，是这个原因吗？

I Start importing pytorch...
D import clients finished
W Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.8.0. This may cause the model to fail to load.
E Catch exception when loading pytorch model: ./zoo/ef0.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 157, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3971, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "/home/zmy/miniconda3/envs/rk/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
E     cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
E RuntimeError: 
E Unknown type name 'NoneType':
E Serialized   File "code/__torch__/torch/nn/modules/linear/___torch_mangle_3484.py", line 6
E   training : bool
E   _is_full_backward_hook : Optional[bool]
E   def forward(self: __torch__.torch.nn.modules.linear.___torch_mangle_3484.Identity) -> NoneType:
E                                                                                         ~~~~~~~~ <--- HERE
E     return None
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by leiqing1** [comment]
你是EfficientNet几啊？

**Comment by MinYounZhang** [comment]
> 你是EfficientNet几啊？

EfficientNet V1 B_3

**Comment by zen-xingle** [comment]
不是，这个应该是 RKNN-Toolkit 依赖的 pytorch 版本与导出模型的 pytorch 版本不一致导致的
