### ISSUE TITLE
init_runtime时报错： NPUTransfer: Cannot connect to proxy: Connection refused And RKNNAPI: rknn_init,  driver open fail!  ret = -4(ERROR_NO_DEVICE)!

### ISSUE THREAD

**Issue by h13-0** [rockchip-linux/rknn-toolkit#214]
CPU：RK3328
系统版本：ubuntu16.04
RK1808 DRV版本：1.7.0
rknn-toolkit-lite版本：1.7.0

使用的yolov3_tiny.rknn为官方demo模型
在windows和linux_x64上运行正常，在arm板子上部署出错。

运行时代码如下：
```
(RKNN_Lite) root@firefly:~/RKNN# python
Python 3.7.2 (default, Jan 11 2019, 18:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rknnlite.api import RKNNLite
>>> rknn = RKNNLite()
>>> rknn.load_rknn("./yolov3_tiny.rknn")
0
>>> rknn.init_runtime(target='rk1808')
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:51)
E NPUTransfer: Cannot connect to proxy: Connection refused
E RKNNAPI: rknn_init,  driver open fail!  ret = -4(ERROR_NO_DEVICE)!
E Catch exception when init runtime!
*************************
all device(s) with ntb mode:
TS018082190800645
*************************
E ['TS018082190800645']
E Traceback (most recent call last):
  File "/opt/archiconda3/envs/RKNN_Lite/lib/python3.7/site-packages/rknnlite/api/rknn_lite.py", line 154, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 417, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE

-1
>>> rknn.init_runtime(target='rk1808', device_id="TS018082190800645")
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:51)
E NPUTransfer: Cannot connect to proxy: Connection refused
E RKNNAPI: rknn_init,  driver open fail!  ret = -4(ERROR_NO_DEVICE)!
E Catch exception when init runtime!
*************************
all device(s) with ntb mode:
TS018082190800645
*************************
E ['TS018082190800645']
E Traceback (most recent call last):
  File "/opt/archiconda3/envs/RKNN_Lite/lib/python3.7/site-packages/rknnlite/api/rknn_lite.py", line 154, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 417, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE

-1
>>> 
```

3328端环境：
```
(RKNN_Lite) root@firefly:~/RKNN# pip list
Package           Version   
----------------- ----------
certifi           2018.10.15
numpy             1.16.3    
pip               10.0.1    
psutil            5.6.2     
rknn-toolkit-lite 1.7.0     
ruamel.yaml       0.15.81   
setuptools        40.4.3    
wheel             0.32.1 
```

ifconfig输出
```
(RKNN_Lite) root@firefly:~/RKNN# ifconfig -a
enx10dcb69f0415: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.180.1  netmask 255.255.255.0  broadcast 192.168.180.255
        inet6 fe80::c130:282:ffa5:ae0a  prefixlen 64  scopeid 0x20<link>
        ether 10:dc:b6:9f:04:15  txqueuelen 1000  (Ethernet)
        RX packets 6887  bytes 798533 (798.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6833  bytes 861229 (861.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
npu_transfer_proxy 输出：
```
(RKNN_Lite) root@firefly:~/RKNN# ./npu_transfer_proxy devices
List of ntb devices attached
TS018082190800645   5bf09205    USB_DEVICE
```

ping和ssh均正常

不知道是什么问题

**Comment by h13-0** [comment]
lsusb输出
```
root@firefly:~# lsusb
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 002: ID 2207:0018  
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 002: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

**Comment by h13-0** [comment]
基本可以排除是3328开发板的问题，我重新在全志H616(ubuntu20)上搭建了环境，报错一致。
应该是加速棒端设置问题或者whl的问题。

**Comment by h13-0** [comment]
问题已解决。
不要在3328上运行rknn_server
后续问题：
https://github.com/rockchip-linux/rknn-toolkit/issues/215

**Comment by samarth1232** [comment]
I am also getting similar kind of error when running model inference using c++ code for ssd mobilnet model 
```
E NPUTransfer: Cannot connect to proxy: Connection refused
E RKNNAPI: rknn_init,  driver open fail!  ret = -4(ERROR_NO_DEVICE)!
rknn_init fail! ret=-3
```

and I am using this code:
https://github.com/rockchip-linux/RKNPUTools/blob/rk33/mid/8.1/develop/rknn-api/Linux/rknn_api_sdk/rknn_ssd.cpp

can anyone help
