### ISSUE TITLE
Converting CNN with only one Conv2D node in ONNX format into RKNN model fails.

### ISSUE THREAD

**Issue by YuyaKobayashi** [rockchip-linux/rknn-toolkit#221]
The below script construct CNN with only one Conv2D node in ONNX, and try to convert it to RKNN model:

```python
#!/usr/bin/env python3

import numpy as np
import onnx
from onnx.helper import make_tensor, make_tensor_value_info, make_model, make_graph, make_node
from onnx import TensorProto, GraphProto, AttributeProto
from rknn.api import RKNN
import onnxruntime


def get_onnx_inout_info(onnx_path):
    model = onnx.load(onnx_path)
    input_names  = []
    input_shapes = []
    output_names = []
    for vinfo in model.graph.input:
        input_names.append(vinfo.name)
        input_shapes.append([d.dim_value for d in vinfo.type.tensor_type.shape.dim])
    for vinfo in model.graph.output:
        output_names.append(vinfo.name)
    return input_names, input_shapes, output_names


def smoke_test_onnx(path, input_shape):
    sess = onnxruntime.InferenceSession(path)
    res = sess.run(["output"], {"input": np.random.rand(*input_shape).astype(np.float32)})


def main():
    np.random.seed(0)
    path = "conv2d.onnx"

    input_shape = (1, 120, 30, 20)
    output_shape = (1, 480, 30, 20)
    weight_shape = (480, 120, 3, 3)
    input_value_info = make_tensor_value_info("input", TensorProto.FLOAT, input_shape)
    output_value_info = make_tensor_value_info("output", TensorProto.FLOAT, output_shape)
    attrs = {
            "pads": (1, 1, 1, 1),
            }

    weight_val = np.random.rand(*weight_shape).astype(np.float32).flatten().tolist()
    bias_val = np.random.rand(weight_shape[0]).astype(np.float32).flatten().tolist()
    weight_tensor = make_tensor("weight", TensorProto.FLOAT, dims=weight_shape, vals=weight_val)
    bias_tensor = make_tensor("bias", TensorProto.FLOAT, dims=weight_shape[:1], vals=bias_val)

    conv_op = make_node("Conv", ["input", "weight", "bias"], ["output"], **attrs)

    graph = make_graph([conv_op], "simple_conv", [input_value_info], [output_value_info], initializer=[weight_tensor, bias_tensor])
    model = make_model(graph, producer_name="dmp")

    onnx.checker.check_model(model)
    onnx.save(model, path)
    smoke_test_onnx(path, input_shape)

    input_names, input_shapes, output_names = get_onnx_inout_info(path)

    rknn_module = RKNN(verbose=True)
    rknn_module.config(batch_size=1, target_platform=["rk1808"])

    ret = rknn_module.load_onnx(path, inputs=input_names, input_size_list=input_shapes, outputs=output_names)
    if ret != 0:
        raise RuntimeError("Failed to load ONNX model")

    ret = rknn_module.export_rknn(rknn_path)
    if ret != 0:
        raise RuntimeError("Failed to export RKNN model")

    rknn_module.release()


if __name__ == '__main__':
    main()
```

However, it stops with the below error message. What is wrong in my code?

```bash
W Verbose file path is invalid, debug info will not dump to file.
W:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
D Using CPPUTILS: True
I Start importing onnx...
W Call onnx.optimizer.optimize fail, skip optimize
I Current ONNX Model use ir_version 6 opset_version 11
I Call RKNN onnx optimize fail, skip optimize
D Calc tensor Initializer_bias (480,)
D Calc tensor Initializer_weight (480, 120, 3, 3)
E Calc node Conv : Conv_0 output shape fail
E Catch exception when loading onnx model: conv2d.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/conv.py", line 40, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.conv.Conv
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/max_pool.py", line 50, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.max_pool.get_output_shape
E IndexError: list index out of range
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 112, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1062, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node Conv : Conv_0 output shape fail
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Traceback (most recent call last):
  File "make_conv2d_onnx.py", line 73, in <module>
    main()
  File "make_conv2d_onnx.py", line 63, in main
    raise RuntimeError("Failed to load ONNX model")
RuntimeError: Failed to load ONNX model
```

# System info
python version - 3.6.9
OS - Ubuntu 18.04 LTS

## Python Package Versions

```
numpy==1.16.3
onnx==1.6.0
onnx-graphsurgeon==0.3.15
onnx-tf==1.2.1
onnxconverter-common==1.9.0
onnxruntime==1.7.0
rknn-toolkit @ file:///home/yuyakobayashi/WORKSPACE/ROCKCHIP/archive/packages/rknn_toolkit-1.7.1-cp36-cp36m-linux_x86_64.whl
skl2onnx==1.11
tf2onnx==1.9.3
```

**Comment by YuyaKobayashi** [comment]
I added Reshape operation that does nothing just before Conv2D and then the script works.
