### ISSUE TITLE
8bit量化没有问题，16bit报错

### ISSUE THREAD

**Issue by bluesky1998** [rockchip-linux/rknn-toolkit#236]
E RKNNAPI: rknn_init,  recv(MsgLoadAck) fail, -9(ERROR_PIPE) != 368!
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 897, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
E Current device id is: None
E Devices connected:
E ['a9e33f8bbed29138']
E Runtime environment is not inited, please call init_runtime to init it first!
E Runtime environment is not inited, please call init_runtime to init it first!

**Comment by DDX1126** [comment]
E Current device id is: None # 没有识别到device，检查一下npu是否识别启动了
E Devices connected:
E ['a9e33f8bbed29138']
