### ISSUE TITLE
语义分割问题：'tensorflow._api.v1.dtypes' has no attribute 'int64'

### ISSUE THREAD

**Issue by GKXKX123456** [rockchip-linux/rknn-toolkit#244]
语义分割网络，在onnx2rknn或者pytorch2rknn时，碰到argmax输出数据类型的问题，问题报错如下：
> E Catch exception when building RKNN model!
> E Traceback (most recent call last):
> E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 437, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
> E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 476, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
> E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 481, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
> E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 293, in rknn.base.RKNNlib.layer.RKNNlayer.RKNNLayer.compute_tensor
> E   File "rknn/base/client/argmax.py", line 51, in rknn.base.client.argmax.ArgMax.compute_out_tensor
> E AttributeError: module 'tensorflow._api.v1.dtypes' has no attribute 'int64'
> E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
> E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
请问有什么解决方案吗？

**Comment by GKXKX123456** [comment]
@airockchip
