### ISSUE TITLE
YOLOX使用pytorch量化工具量化后，无法被rknn加载

### ISSUE THREAD

**Issue by wuzhenyusjtu** [rockchip-linux/rknn-toolkit#245]
yolox_pt_test/yolox_qnnpack.torchscript.pt ********************
W The pt model is quantized. User can try to set 'quantize_input_node=True' and 'merge_dequant_layer_and_output_node=True' in rknn.config. These setting may accelerate the inferencing on rknpu devices
E Catch exception when loading pytorch model: yolox_pt_test/yolox_qnnpack_160.torchscript.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 157, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3985, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 4190, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
**E AssertionError: Inputs of graph output 62 should be layer.**

**Comment by WangFengtu1996** [comment]
@wuzhenyusjtu  
* Hello, 问下你最终在rknn上成功部署了 yolox了么，yolox所有的算子都能被支持么？
