### ISSUE TITLE
RK3399Pro更新rknpu后rknn.init_runtime报错

### ISSUE THREAD

**Issue by itcolossus** [rockchip-linux/rknn-toolkit#265]
我的板子是RK3399Pro debian系统

1、更新https://github.com/rockchip-linux/rknpu 替换rk3399pro代码仓库下的npu/external/rknpu，然后编译替换之前的npu固件
2、rk3399pro开发板上安装rknn_toolkit-1.7.1-cp37-cp37m-linux_aarch64.whl
3、adb push rknn-toolkit/platform-tools/ntp/linux-aarch64/npu_transfer_proxy 到debian下的/usr/bin 替换旧的
4、运行mobilenet_v1，报一下错误。

done
--> Export RKNN model
done
--> Init runtime environment
E Catch exception when init runtime!
E Traceback (most recent call last):
E File "rknn/api/rknn_base.py", line 868, in rknn.api.rknn_base.RKNNBase.init_runtime
E File "rknn/api/rknn_runtime.py", line 163, in rknn.api.rknn_runtime.RKNNRuntime.init
E File "rknn/api/rknn_runtime.py", line 228, in rknn.api.rknn_runtime.RKNNRuntime._load_library
E File "/usr/lib/python3.7/ctypes/init.py", line 356, in init
E self._handle = _dlopen(self._name, mode)
E OSError: libOpenVX.so.1.2: cannot open shared object file: No such file or directory
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Init runtime environment failed

**Comment by zen-xingle** [comment]
RK3399pro is special, use this https://github.com/airockchip/RK3399Pro_npu
