### ISSUE TITLE
Loading pytorch model fails for input_size_list = [[1, 352, 128, 4]]

### ISSUE THREAD

**Issue by sahi1422** [rockchip-linux/rknn-toolkit#269]
Below code fails:
```
    input_size_list = [[1, 352, 128, 4]]

    # Create RKNN object
    rknn = RKNN()

    # pre-process config
    print('--> Config model')
    rknn.config()
    print('done')

    # Load Pytorch model
    print('--> Loading model')
    ret = rknn.load_pytorch(model=trace_model_path, input_size_list=input_size_list)
    if ret != 0:
        print('Load Pytorch model failed!')
        exit(ret)
    print('done')
```
Logs:
```
--> Config model
done
--> Loading model
./trace_alandi.pt ********************
W Warning: Axis may need to be adjusted according to original model shape.
E 352 inputs, more than 16 inputs is not support in concat layer!
E Catch exception when loading pytorch model: ./trace_alandi.pt!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3783, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.convert_operators
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 714, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.cat
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 228, in rknn.base.RKNNlib.converter.convert_pytorch_new._set_layer_out_shape
E   File "rknn/base/RKNNlib/layer/concat.py", line 37, in rknn.base.RKNNlib.layer.concat.Concat.compute_out_shape
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: 352 inputs, more than 16 inputs is not support in concat layer!
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Load Pytorch model failed!
```

**Comment by zen-xingle** [comment]
hello, actually this error is caused by "more than 16 inputs is not support in concat layer!". Concat got a limited that up to 16 tensors is allowed. If you want to avoid this error, try to gen more concats to avoid the 16 limit. 
Just like concat([t0, ... t31]) = concat(  [concat([t0,...t15]), concat([t16, ...,t32])] )

But there is still a problem that concat layer is easy to got accuracy drop if there are too much tensors as inputs for the concat layer.
