### ISSUE TITLE
E Try match layer: Pad_Pad_14:out0 failed! The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!

### ISSUE THREAD

**Issue by ttttttt12** [rockchip-linux/rknn-toolkit#275]
--> Config model
done
--> Loading model
W Call onnx.optimizer.optimize fail, skip optimize
/usr/local/lib/python3.6/dist-packages/rknn/api/rknn.py:150: RuntimeWarning: overflow encountered in exp
  ret = self.rknn_base.load_onnx(model, inputs, input_size_list, outputs)
W The follow op is not support : ['ConstantOfShape']
W Not match tensor Pad_Pad_14:out0 
E Try match layer: Pad_Pad_14:out0 failed!
The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Catch exception when loading onnx model: ./best_model_freeze.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1710, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1602, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 292, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 129, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1718, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match layer: Pad_Pad_14:out0 failed!
E The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Load onnx model failed!

I can't convert onnx to rknn, I need help~~

**Comment by zen-xingle** [comment]
Hello. 1.7.3 version is released, you can try to use the new version. Or you can try https://github.com/daquexian/onnx-simplifier to simplify the onnx model the feed it to RKNN-Toolkit
