### ISSUE TITLE
jit-pt 转rknn失败

### ISSUE THREAD

**Issue by BaseJiang** [rockchip-linux/rknn-toolkit#279]
训练的yolov3+mobilenet v2模型, 先转onnx 再转rknn,可以正常实现,运行推断也正常.

但是将训练的模型,通过orch.jit.trace()接口转换后,再转rknn时候,在load模型的时候,rknn.load_pytorch()接口出错.

转换程序如下:
D Output shape of layer slice_at_conv_raw_prob.2_345_299: [[1, 9, 64, 64, -2]]
I Parse prim::Constant at 3859
I Parse aten::arange at 3860
I Parse aten::unsqueeze at 3861
I Parse prim::ListConstruct at 3862
I Parse aten::repeat at y.2
I Parse prim::Constant at 3864
I Parse aten::arange at 3865
I Parse aten::unsqueeze at 3866
I Parse prim::ListConstruct at 3867
I Parse aten::repeat at x.2
I Parse prim::ListConstruct at 3869
I Parse aten::stack at grid_xy.2
E Data type of constant data of layer: var_at_grid_xy.2_353_301 is <class 'list'>, which is not supported!
Load pytorch model failed!
E Catch exception when loading pytorch model: ./model_file/backup_epoch13000_network_jit.pt!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 4156, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3783, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.convert_operators
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2771, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.stack
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 335, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter._gen_variable_layer
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Data type of constant data of layer: var_at_grid_xy.2_353_301 is <class 'list'>, which is not supported!
E Please feedback the detailed log file <verbose_log.txt> to the RKNN Toolkit development team.

报错信息如下:
D Output shape of layer slice_at_conv_raw_prob.2_345_299: [[1, 9, 64, 64, -2]]
I Parse prim::Constant at 3859
I Parse aten::arange at 3860
I Parse aten::unsqueeze at 3861
I Parse prim::ListConstruct at 3862
I Parse aten::repeat at y.2
I Parse prim::Constant at 3864
I Parse aten::arange at 3865
I Parse aten::unsqueeze at 3866
I Parse prim::ListConstruct at 3867
I Parse aten::repeat at x.2
I Parse prim::ListConstruct at 3869
I Parse aten::stack at grid_xy.2
E Data type of constant data of layer: var_at_grid_xy.2_353_301 is <class 'list'>, which is not supported!
Load pytorch model failed!
E Catch exception when loading pytorch model: ./model_file/backup_epoch13000_network_jit.pt!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 4156, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3783, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.convert_operators
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2771, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.stack
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 335, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter._gen_variable_layer
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Data type of constant data of layer: var_at_grid_xy.2_353_301 is <class 'list'>, which is not supported!
E Please feedback the detailed log file <verbose_log.txt> to the RKNN Toolkit development team.

**Comment by zen-xingle** [comment]
1.7.3版本已经发布，可以试下新版本是否仍有此问题，仍然存在的话，可以上传模型，我们复现下问题
