### ISSUE TITLE
rknn-toolkit 1.4.0 cannot support OP global_pool

### ISSUE THREAD

**Issue by wang911205** [rockchip-linux/rknn-toolkit#28]
mxnet中pooling实现: {
"op": "Pooling",
"name": "vargface_head_head_pooling_se_pool1",
"attrs": {
"global_pool": "True",
"pool_type": "avg"
},
"inputs": 45, 0, 0
}

报错：
root@ba1aee2d3c30:/desktop/RK1808/examples/mxnet/resnext50# python test_mx1.py
--> config model
done
--> Loading model
Load MXnet model
/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py:1159: UserWarning: Cannot decide type for the following arguments. Consider providing them as input:
data: None
input_sym_arg_type = in_param.infer_type()[0]
Parsing net
W Rename minusscalar0_variable to rknn_minusscalar0_variable
W Rename minusscalar0 to rknn_minusscalar0
W Rename mulscalar0_variable to rknn_mulscalar0_variable
W Rename mulscalar0 to rknn_mulscalar0
W Rename mul0 to rknn_mul0
W Rename mul2 to rknn_mul2
W Rename mul3 to rknn_mul3
W Rename mul4 to rknn_mul4
E Catch exception when loading mxnet model: ./model-v-arcface-clean-original-symbol.json!
E Traceback (most recent call last):
E File "rknn/api/rknn_base.py", line 677, in rknn.api.rknn_base.RKNNBase.load_mxnet
E File "rknn/base/RKNNlib/app/importer/mxnetloader.py", line 661, in rknn.base.RKNNlib.app.importer.mxnetloader.MxnetLoader.load
E File "rknn/base/RKNNlib/app/importer/mxnetloader.py", line 549, in rknn.base.RKNNlib.app.importer.mxnetloader.MxnetLoader.parse_nets
E File "rknn/base/RKNNlib/app/importer/mxnetloader.py", line 380, in rknn.base.RKNNlib.app.importer.mxnetloader.MxnetLoader.parse_layer_params
E File "rknn/base/RKNNlib/app/importer/mxlayer_parse.py", line 228, in rknn.base.RKNNlib.app.importer.mxlayer_parse.parse_pool_param
E KeyError: 'kernel'
Load mxnet model failed!

**Comment by Bohrhh** [comment]
does rknn support custom operations?

**Comment by dasol92** [comment]
@Bohrhh  Yes. Please refer to [this](https://github.com/rockchip-linux/rknn-toolkit/blob/master/doc/Rockchip_Developer_Guide_RKNN_Toolkit_Custom_OP_V1.4.0_EN.pdf).
