### ISSUE TITLE
Init Runtime Fails with  "Execute ntp_transfer_proxy devices failed, permission denied"

### ISSUE THREAD

**Issue by Casta-mere** [rockchip-linux/rknn-toolkit#281]
Hello,
I got the following error when running the test.py in the demo

`
E Execute ntp_transfer_proxy devices failed, ret code: 126. /bin/sh: 1: /usr/local/lib/python3.7/dist-packages/rknn/3rdparty/platform-tools/ntp/linux-aarch64/npu_transfer_proxy: Permission denied

E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 815, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 170, in rknn.api.rknn_runtime.RKNNRuntime.__init__
E   File "rknn/api/rknn_platform_utils.py", line 294, in rknn.api.rknn_platform_utils.start_ntp_or_adb
E   File "rknn/api/rknn_platform_utils.py", line 154, in rknn.api.rknn_platform_utils.weather_device_use_ntb
E Exception: Init runtime environment failed!
`
Here says permission denied
Init runtime environment failed
What should I do?
Thanks.

**Comment by batchsize** [comment]
Maybe permission problem.
Try `chmod+x or 777` 
`chmod +x  /usr/local/lib/python3.7/dist-packages/rknn/3rdparty/platform-tools/ntp/linux-aarch64/npu_transfer_proxy`
