### ISSUE TITLE
tph-YOLOv5模型onnx转rknn报错

### ISSUE THREAD

**Issue by mmasterer** [rockchip-linux/rknn-toolkit#296]
D import clients finished
W Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.8.0. This may cause the model to fail to load.
Load resnet50v2 failed!
E Catch exception when loading pytorch model: 521.pt!
E Traceback (most recent call last):
E   File "rknn\api\rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn\base\RKNNlib\RK_nn.py", line 157, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn\base\RKNNlib\app\importer\import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 3978, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 3770, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.report_missing_conversion
E NotImplementedError: The following operators are not implemented: ['aten::rsub', 'aten::index', 'aten::remainder', 'aten::unbind', 'aten::gelu']
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by DDX1126** [comment]
可以试试转成onnx在转rknn，相关的教程可以参考https://blog.csdn.net/weixin_43999691/article/details/126283992?spm=1001.2014.3001.5502
