### ISSUE TITLE
Your model ir_version is higher than the checker's.

### ISSUE THREAD

**Issue by 18310837090** [rockchip-linux/rknn-toolkit#31]
I am a pt model trained by yolov5, and the training environment is torch1.6. When I use the toolkit's onnx conversion, it prompts an error Your model ir_version is higher than the checker's. It should be that the onnx version is too low, I try to increase the onnx version to 1.7. 0, but it is not compatible with the toolkit, it only supports the highest version to 1.4.1. What should I do, can someone help me?
这是翻译：我是yolov5训练的pt模型，训练环境是torch1.6.在我使用toolkit的onnx转换时候，提示报错Your model ir_version is higher than the checker's.应该是onnx版本太低，我尝试提高onnx版本到1.7.0，但是与toolkit工具不兼容，它只支持最高版本到1.4.1.我应该怎么
做，有人可以帮助我吗？

**Comment by tobyhijzen** [comment]
I am experiencing a similar problem:
```
E Catch exception when loading onnx model: socket_v4.0.onnx!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 510, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 494, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 497, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 86, in check_model
E     C.check_model(model.SerializeToString())
E onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.
```
onnx 1.8.0 support would be great

**Comment by lswgh** [comment]
你好，请问你转rknn 转成功了吗

**Comment by tobyhijzen** [comment]
I'm afraid not
