### ISSUE TITLE
Paddle2onnx, 然后onnx2rknn的时候, 报错"The follow op is not support : ['Resize']"

### ISSUE THREAD

**Issue by fxs628** [rockchip-linux/rknn-toolkit#315]
你好：
    我在把Paddle的官方PP-LiteSeg-T模型(在Cityscapes数据集上miou为73.10%的那个预训练模型)转换为rknn模型时遇到了问题，使用的rknn-toolkit版本为1.7.3，希望获取帮助，谢谢！
步骤：
1、使用paddle将预训练模型导出为预测模型的格式；
2、使用paddle2onnx将模型转换为onnx；
3、使用onnxsim简化；
4、将简化后的onnx模型转换为rknn；
转换为rknn时报错，报错如下：
python.exe .\test.py
--> Config model
done
--> Loading model
W Call onnx.optimizer.optimize fail, skip optimize
W The follow op is not support : ['Resize']
W Not match tensor Resize_p2o.Resize.6:out0
E Try match layer: Resize_p2o.Resize.6:out0 failed!
The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Catch exception when loading onnx model: output_sim.onnx!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1837, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1716, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn\api\rknn_base.py", line 315, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn\base\RKNNlib\RK_nn.py", line 145, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn\base\RKNNlib\app\importer\import_onnx.py", line 129, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1845, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn\api\rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match layer: Resize_p2o.Resize.6:out0 failed!
E The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Load failed!

**Comment by fxs628** [comment]
转化模型的目标平台是RV1126.

**Comment by DDX1126** [comment]
我看1.7.1的op都支持RESIZE的，换成1.7.1看看

**Comment by lucci17** [comment]
> 我看1.7.1的op都支持RESIZE的，换成1.7.1看看

我测试1.7.1也遇到同样问题，我用rknn-toolkit2可以

**Comment by alex-ht** [comment]
Paddle2onnx轉PPOCRv3，出現類似的問題，Reshape應該有支援才對
```
W Not match tensor Reshape_p2o.Reshape.23:out0 
E Try match layer: Reshape_p2o.Reshape.23:out0 failed!
The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Catch exception when loading onnx model: model_fix.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1710, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1602, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 292, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 129, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1718, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match layer: Reshape_p2o.Reshape.23:out0 failed!
E The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

```
