### ISSUE TITLE
pytorch转rknn1126,是不支持torch.cat吗

### ISSUE THREAD

**Issue by Jiangyun475** [rockchip-linux/rknn-toolkit#316]
E Try match layer: Resize_Resize_1382:out0 failed!
The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Catch exception when loading onnx model: res34_test.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1710, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1602, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 292, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 129, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1718, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match layer: Resize_Resize_1382:out0 failed!
E The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Load Pytorch model failed!

**Comment by Jiangyun475** [comment]
> E Try match layer: Resize_Resize_1382:out0 failed! The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>! E Catch exception when loading onnx model: res34_test.onnx! E Traceback (most recent call last): E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1710, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1602, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor E TypeError: 'NoneType' object is not iterable E During handling of the above exception, another exception occurred: E Traceback (most recent call last): E File "rknn/api/rknn_base.py", line 292, in rknn.api.rknn_base.RKNNBase.load_onnx E File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx E File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 129, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1718, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param E File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e E ValueError: Try match layer: Resize_Resize_1382:out0 failed! E The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>! E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team. E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues Load Pytorch model failed!

![image](https://user-images.githubusercontent.com/73049981/201621779-2e7cb76a-1d16-4a06-a2f7-a95eb21effef.png)
