### ISSUE TITLE
加载hybridnets.pt，提示ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by Chnnnne** [rockchip-linux/rknn-toolkit#318]
源码：

```python
import numpy as np
import cv2
from rknn.api import RKNN
import torchvision.models as models
import torch

if __name__ == '__main__':
    model = './hybridnets.pt'
    input_size_list = [[3, 1280, 720]]

    # Create RKNN object
    rknn = RKNN()

    # pre-process config
    print('--> Config model')
    rknn.config(mean_values=[[123.675, 116.28, 103.53]], std_values=[[58.395, 58.395, 58.395]], reorder_channel='1 2 3')
    print('done')

    # Load Pytorch model
    print('--> Loading model')
    ret = rknn.load_pytorch(model=model, input_size_list=input_size_list)
    if ret != 0:
        print('Load Pytorch model failed!')
        exit(ret)
    print('done')

    # Build model
    print('--> Building model')
    ret = rknn.build(do_quantization=True, dataset='./dataset.txt')
    if ret != 0:
        print('Build model failed!')
        exit(ret)
    print('done')

    # Export RKNN model
    print('--> Export RKNN model')
    ret = rknn.export_rknn('./hybridnets.rknn')
    if ret != 0:
        print('Export hybridnets.rknn failed!')
        exit(ret)
    print('done')

    # ret = rknn.load_rknn('./resnet_18.rknn')

    # # Set inputs
    # img = cv2.imread('./space_shuttle_224.jpg')
    # img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # # Init runtime environment
    # print('--> Init runtime environment')
    # ret = rknn.init_runtime()
    # if ret != 0:
    #     print('Init runtime environment failed')
    #     exit(ret)
    # print('done')

    # # Inference
    # print('--> Running model')
    # outputs = rknn.inference(inputs=[img])
    # show_outputs(softmax(np.array(outputs[0][0])))
    # print('done')

    rknn.release()

```

报错信息：
```
W Detect torchvision(0.11.3). If the python program got segment fault error, try to <import tensorflow> before <import torchvision>
--> Config model
done
--> Loading model
./hybridnets.pt ********************
W Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.10.2+cpu. This may cause the model to fail to load.
W Warning: Axis may need to be adjusted according to original model shape.
W Warning: Axis may need to be adjusted according to original model shape.
W:tensorflow:From D:\develop\anaconda3\envs\py36\lib\site-packages\rknn\api\rknn.py:217: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W:tensorflow:From D:\develop\anaconda3\envs\py36\lib\site-packages\rknn\api\rknn.py:217: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W:tensorflow:From D:\develop\anaconda3\envs\py36\lib\site-packages\rknn\api\rknn.py:217: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Load Pytorch model failed!
E Catch exception when loading pytorch model: ./hybridnets.pt!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\RKNNnetbuilder.py", line 437, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   File "rknn\base\RKNNlib\RKNNnetbuilder.py", line 437, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   File "rknn\base\RKNNlib\RKNNnetbuilder.py", line 437, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   [Previous line repeated 1 more time]
E   File "rknn\base\RKNNlib\RKNNnetbuilder.py", line 435, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E ValueError: need more than 1 value to unpack
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

Process finished with exit code -1

```

**Comment by klamiory** [comment]
同样在加载pytorch model的时候遇到了这个问题，请问下后来是咋解决的

**Comment by hjl66662** [comment]
您好，请问您当初解决这个问题了吗

**Comment by S0soo** [comment]
> 您好，请问您当初解决这个问题了吗

请问您解决了这个问题么

**Comment by hjl66662** [comment]
> > 您好，请问您当初解决这个问题了吗
> 
> 请问您解决了这个问题么

无，换模型了
