### ISSUE TITLE
pytorch模型转rknn报错 E AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by sglshanghai** [rockchip-linux/rknn-toolkit#325]
rknn-toolkit版本为V1.7.3，build model时报错，信息如下：

--> Building model
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 624, in rknn.api.rknn_base.RKNNBase.build
E   File "rknn/api/rknn_base.py", line 2877, in rknn.api.rknn_base.RKNNBase._generate_inputmeta
E AttributeError: 'list' object has no attribute 'split'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Build pytorch failed!

**Comment by wavelet2008** [comment]
同样的问题

**Comment by jun214384468** [comment]
同样的问题

**Comment by tianchongchong** [comment]
同样的问题

**Comment by wqcsim** [comment]
同样的问题 
E Catch exception when loading onnx model: ./optimize.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 26, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.Reshape
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 13, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.reshape_reference_implementation
E AttributeError: 'list' object has no attribute 'shape'
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 120, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 123, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1187, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e

**Comment by kuby-dl** [comment]
> 同样的问题 E Catch exception when loading onnx model: ./optimize.onnx! E Traceback (most recent call last): E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 26, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.Reshape E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 13, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.reshape_reference_implementation E AttributeError: 'list' object has no attribute 'shape' E During handling of the above exception, another exception occurred: E Traceback (most recent call last): E File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 120, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 123, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.**init** E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1187, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape E File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e

Hi, I face the same issue, did you resolve it already?

**Comment by LiYf169** [comment]
> > 同样的问题 E Catch exception when loading onnx model: ./optimize.onnx! E Traceback (most recent call last): E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 26, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.Reshape E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 13, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.reshape_reference_implementation E AttributeError: 'list' object has no attribute 'shape' E During handling of the above exception, another exception occurred: E Traceback (most recent call last): E File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 120, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 123, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.**init** E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1187, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape E File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
> 
> Hi, I face the same issue, did you resolve it already?

解决了吗？

**Comment by LiYf169** [comment]
> 同样的问题 E Catch exception when loading onnx model: ./optimize.onnx! E Traceback (most recent call last): E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 26, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.Reshape E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/reshape.py", line 13, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.reshape.reshape_reference_implementation E AttributeError: 'list' object has no attribute 'shape' E During handling of the above exception, another exception occurred: E Traceback (most recent call last): E File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 120, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 123, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.**init** E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1187, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape E File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e

解决了吗？
