### ISSUE TITLE
Catch exception when building RKNN model.

### ISSUE THREAD

**Issue by huanmei9** [rockchip-linux/rknn-toolkit#328]
1. model type: ONNX
2. toolkit version: v1.7.3
3. bug info: 
```
E Catch exception when building RKNN model! 
E Traceback (most recent call last): 
E   File "rknn/base/RKNNlib/RKNNnet.py", line 672, in rknn.base.RKNNlib.RKNNnet.RKNNNet.load_input_meta 
E   File "rknn/base/RKNNlib/RKNNnet.py", line 675, in rknn.base.RKNNlib.RKNNnet.RKNNNet.load_input_meta 
E   File "rknn/base/RKNNlib/RKNNnet.py", line 398, in rknn.base.RKNNlib.RKNNnet.RKNNNet.update_input_meta 
E   File "rknn/base/RKNNlib/net_input_meta.py", line 20, in rknn.base.RKNNlib.net_input_meta.NetInputMeta.__init__ 
E   File "rknn/base/RKNNlib/net_input_meta.py", line 59, in rknn.base.RKNNlib.net_input_meta.DatabaseMeta.__init__ 
E AssertionError 
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team. 
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
```
4. detailed log file:
```
(skip)
...
D RKNN output shape(permute): (1 512 512 3)
D Tensor @Transpose_Transpose_290_1:out0 type: float32
D Process attach_Transpose_Transpose_290/out0_0 ...
D RKNN output shape(output): (1 512 512 3)
D Tensor @attach_Transpose_Transpose_290/out0_0:out0 type: float32
I Build torch-jit-export complete.
D Optimizing network with EBL_Linear_large_feature_seperate, HFD_cumsum_to_conv2d, HFD_conv1d_to_2d, HFD_conv1d_dilation_opt, HFD_buffer_operation_excute_immediately, HFD_argmin_argmax_output_dequant, HFD_bn1d_to_bn2d, HFD_matmul_shape_hack, HP_deconvolution_optimize
I Start C2T Switcher...
D Optimizing network with broadcast_op, remove_cast
D convert Concat_Concat_271_24(concat) axis 1 to 3
D convert Concat_Concat_281_9(concat) axis 1 to 3
D insert permute attach_Transpose_Transpose_290/out0_0_RKNN_mark_perm_273 before attach_Transpose_Transpose_290/out0_0
D insert permute Transpose_Transpose_288_3_RKNN_mark_perm_274 before Transpose_Transpose_288_3
D remove permute Transpose_Transpose_288_3_RKNN_mark_perm_274
D Convert permute parameter [0 3 2 1] to [0, 2, 1, 3]
D remove permute Transpose_Transpose_290_1
D Convert permute parameter [0 2 3 1] to [0, 2, 1, 3]
I End C2T Switcher...
D Optimizing network with force_1d_tensor, swapper, merge_duplicate_quantize_dequantize, merge_layer, auto_fill_bn, auto_fill_l2normalizescale, auto_fill_instancenormalize, resize_nearest_transformer, eltwise_transform, auto_fill_multiply, auto_fill_zero_bias, proposal_opt_import, special_add_to_conv2d
D Fill zero bias for Conv_Conv_282_8 (convolution)
D Fill zero bias for Conv_Conv_274_16 (convolution)
D Fill zero bias for Conv_Conv_240_46 (convolution)
D Fill zero bias for Conv_Conv_243_47 (convolution)
D Fill zero bias for Conv_Conv_246_48 (convolution)
I Extend eltwise(SUM) layer Add_Add_9_35.
I Extend eltwise(SUM) layer Add_Add_222_58.
I End importing onnx...
I Generate input meta ...
I Load input meta
I Generate input meta ...
D import clients finished
I Load net...
I Load data...
I Load input meta
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RKNNnet.py", line 672, in rknn.base.RKNNlib.RKNNnet.RKNNNet.load_input_meta
E   File "rknn/base/RKNNlib/RKNNnet.py", line 675, in rknn.base.RKNNlib.RKNNnet.RKNNNet.load_input_meta
E   File "rknn/base/RKNNlib/RKNNnet.py", line 398, in rknn.base.RKNNlib.RKNNnet.RKNNNet.update_input_meta
E   File "rknn/base/RKNNlib/net_input_meta.py", line 20, in rknn.base.RKNNlib.net_input_meta.NetInputMeta.__init__
E   File "rknn/base/RKNNlib/net_input_meta.py", line 59, in rknn.base.RKNNlib.net_input_meta.DatabaseMeta.__init__
E AssertionError
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
```

Could anyone help me to fix it?

Thanks.

**Comment by huanmei9** [comment]
Tips: When i use rknn-toolkit v1.7.3 and v1.7.1 in docker environment, I have the same bug.

**Comment by nadhiranoor** [comment]
how do you fix this?
