### ISSUE TITLE
yolo5 err

### ISSUE THREAD

**Issue by xuyi2005** [rockchip-linux/rknn-toolkit#329]
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\ops\slice.py", line 41, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.slice.Slice
E   File "<string>", line 1, in <module>
E TypeError: slice indices must be integers or None or have an __index__ method
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\app\importer\import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 115, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1161, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn\api\rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node Slice : /model.2/model.2.0/Slice output shape fail

**Comment by xuyi2005** [comment]
E TypeError: slice indices must be integers or None or have an index method???!!!

**Comment by zen-xingle** [comment]
for yolov5/yolov7/yolox, refer here https://github.com/airockchip/rknn_model_zoo/tree/main/models/CV/object_detection/yolo

**Comment by sankexin** [comment]
I met another slice problem，solve by：
# pip install onnxsim
python -m onnxsim xxx.onnx xxx_sim.onnx
