### ISSUE TITLE
tflite conversion to rknn  'rknn.build(do_quantization=True, dataset='/home/linaro/dataset.txt', pre_compile=False)'

### ISSUE THREAD

**Issue by marco0913** [rockchip-linux/rknn-toolkit#331]
_I am trying to convert a tflite model to a quantized rknn model:
images and the dataset.txt file containing the images path are in the same directory._

_dataset.txt  contains 150 rows and looks like this:_
egg_1.jpg
egg_2.jpg
egg_3.jpg

_below is the code I am using_

# Create RKNN object
rknn = RKNN()
print('--> config model')
rknn.config(target_platform='rk3399pro',reorder_channel='0 1 2', quantized_dtype= 'asymmetric_quantized-u8')

print('--> Loading model')
ret = rknn.load_tflite(model = 'model)
if ret != 0:
    print('Load failed!')
    exit(ret)
print('done')

# Build model
print('--> Building model')
ret = rknn.build(do_quantization=True, dataset='/home/linaro/dataset.txt', pre_compile=False)
if ret != 0:
    print('Build *.rknn failed!')
    exit(ret)
print('done')

# Export rknn model
print('--> Export RKNN model')
ret = rknn.export_rknn("ai-quant.rknn")
if ret != 0:
    print('Export *.rknn failed!')
    exit(ret)
print('done')

_however I am getting this error:_

**--> config model
config done
--> Loading model
--> Building model**
[33mW Can not find file: ﻿egg_1.jpg. This line will be ignored![0m
[33mW 2 blank line(s) in dataset file. Ignored!!![0m
[31mE There is no valid data in the dataset: /home/linaro/dataset.txt. Please check it.[0m
[31mE Catch exception when building RKNN model![0m
[31mE Traceback (most recent call last):[0m
[31mE   File "rknn/base/RKNNlib/RK_nn.py", line 559, in rknn.base.RKNNlib.RK_nn.RKnn.quantize[0m
[31mE   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 42, in rknn.base.RKNNlib.app.medusa.quantization.Quantization.__init__[0m
[31mE   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 68, in rknn.base.RKNNlib.app.medusa.workspace.Workspace.__init__[0m
[31mE   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 131, in rknn.base.RKNNlib.app.medusa.workspace.Workspace.update_net_batch_size[0m
[31mE   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e[0m
[31mE ValueError: There is no valid data in the dataset: /home/linaro/dataset.txt. Please check it.[0m
[31mE Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.[0m
[31mE You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues[0m
**Build .rknn failed!**

**Comment by Essie999** [comment]
Did you solve it？ I also met this problem

**Comment by marco0913** [comment]
Yes, I solved it by creating the txt file from terminal with sudo nano dataset.txt, somehow it wasn't recognizing the dataset file when created outside the terminal. However whenever I convert the tflite to rknn I lose accuracy around 10-15%, please let me know if you are facing the same issue.
