### ISSUE TITLE
yolov5 pytorch convert to rknn fail

### ISSUE THREAD

**Issue by 304526881** [rockchip-linux/rknn-toolkit#334]
E Catch exception when loading pytorch model: ./../../../../../../model/v1.0.10.torchscript.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 399, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 161, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 5113, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 275, in load
E     cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
E RuntimeError: 
E aten::_convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool benchmark, bool deterministic, bool cudnn_enabled) -> (Tensor):
E Expected at most 12 arguments but found 13 positional arguments.
E :
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/conv.py(439): _conv_forward
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/conv.py(443): forward
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
E /media/lvm/home/aa/tjh/fish_detect/yolov5_tjh/models/common.py(50): forward_fuse
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
E /media/lvm/home/aa/tjh/fish_detect/yolov5_tjh/models/yolo.py(173): _forward_once
E /media/lvm/home/aa/tjh/fish_detect/yolov5_tjh/models/yolo.py(147): forward
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/jit/_trace.py(952): trace_module
E /media/lvm/home/aa/anaconda3/envs/yolo5s/lib/python3.8/site-packages/torch/jit/_trace.py(735): trace
E export.py(57): export_torchscript

yolov5 模型 基于pytorch的转为rknn模型失败

**Comment by DDX1126** [comment]
导出onnx试试吧

**Comment by weishibo-mudanglu** [comment]
rknn依赖的torch版本和模型生成的torch版本不一致导致的，同步一下版本就能解决
