### ISSUE TITLE
ShuffleNetv2转rknn失败

### ISSUE THREAD

**Issue by mmasterer** [rockchip-linux/rknn-toolkit#335]
将shufflenetv2转onnx，在转rknn时报错
E   File "<string>", line 1, in <module>
E TypeError: slice indices must be integers or None or have an __index__ method
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\app\importer\import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 112, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1062, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn\api\rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node Slice : Slice_27 output shape fail
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Traceback (most recent call last):
  File "F:/tr/rk.py", line 34, in <module>
    rknn.build(do_quantization=True,dataset='./dataset.txt',pre_compile=False)
  File "D:\anaconda3\envs\rknn\lib\site-packages\rknn\api\rknn.py", line 262, in build
    inputs = self.rknn_base.net.get_input_layers()
AttributeError: 'NoneType' object has no attribute 'get_input_layers'
是这个（ Slice_27 output shape fail）算子不支持吗

**Comment by XiXinSun** [comment]
请问您最后是怎么解决的

**Comment by mmasterer** [comment]
把这个算子用其他函数替代掉

**Comment by XiXinSun** [comment]
> > 请问您最后是怎么解决的
> 
> 把这个算子用其他方法替代掉

好的，您是使用什么方法替换掉的呢

**Comment by mmasterer** [comment]
> > > 请问您最后是怎么解决的
> > 
> > 
> > 把这个算子用其他方法替代掉
> 
> 好的，您是使用什么方法替换掉的呢

把 x1,x2=x.chunk(2,1)用
x=x.split(int(x.shape[1]/2),1dim=1)
x1,x2=x[0],x[1]代替，就能转成rknn了
