### ISSUE TITLE
rknn-toolkit-1.7.3导入pytorch量化模型，提示不支持['quantized::relu6']

### ISSUE THREAD

**Issue by Spratumn** [rockchip-linux/rknn-toolkit#336]
```
Using CPPUTILS: True
I Start importing pytorch...
D import clients finished
W Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.9.1+cpu. This may cause the model to fail to load.
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 399, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 161, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 5120, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 4902, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.report_missing_conversion
E NotImplementedError: The following operators are not implemented: ['quantized::relu6']
E Please feedback the detailed log file <yolox_v8_non-compile_rk3399pro_960-576_b1.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
```

**Comment by Spratumn** [comment]
转换代码是参考的官方example
![image](https://user-images.githubusercontent.com/32872875/212235317-c610e5a1-7627-476c-b6a6-b54cdf013901.png)

**Comment by Spratumn** [comment]
转换代码是参考的官方example
![image](https://user-images.githubusercontent.com/32872875/212235853-d8b24918-bb5c-453e-a3b9-d6d2e4cc6030.png)
