### ISSUE TITLE
pip install /packages/rknn_toolkit-1.7.3-cp38-cp38-linux_x86_64.whl  onnx 1.6.0  version do not support

### ISSUE THREAD

**Issue by Amanda-Qu** [rockchip-linux/rknn-toolkit#339]
ERROR: Failed building wheel for onnx

I find when I install rknn_toolkit-1.7.3, it will automatically install onnx 1.6.0，It raise error as above.

when I  checked the onnx version at: https://pypi.org/project/onnx/1.7.0/#files,  onnx does not support python vesion larger than 3.7.

So pthon 3.8 in rknn_toolkit-1.7.3-cp38-cp38-linux_x86_64.whl  is confilcted with onnx's python version?

Any solutions or anyone can help? Many thanks.

    
      --
      -- ******** Summary ********
      --   CMake version         : 3.25.0
      --   CMake command         : /home/ai/venv/rknn/lib/python3.8/site-packages/cmake/data/bin/cmake
      --   System                : Linux
      --   C++ compiler          : /usr/bin/c++
      --   C++ compiler version  : 11.3.0
      --   CXX flags             :  -Wnon-virtual-dtor
      --   Build type            : Release
      --   Compile definitions   :
      --   CMAKE_PREFIX_PATH     :
      --   CMAKE_INSTALL_PREFIX  : /usr/local
      --   CMAKE_MODULE_PATH     :
      --
      --   ONNX version          : 1.6.0
      --   ONNX NAMESPACE        : onnx
      --   ONNX_BUILD_TESTS      : OFF
      --   ONNX_BUILD_BENCHMARKS : OFF
      --   ONNX_USE_LITE_PROTO   : OFF
      --   ONNXIFI_DUMMY_BACKEND : OFF
      --   ONNXIFI_ENABLE_EXT    : OFF
      --
      --   Protobuf compiler     : /usr/bin/protoc
      --   Protobuf includes     : /usr/include
      --   Protobuf libraries    : /usr/lib/x86_64-linux-gnu/libprotobuf.so
      --   BUILD_ONNX_PYTHON     : ON
      --     Python version      :
      --     Python executable   : /home/ai/venv/rknn/bin/python3
      --     Python includes     : /usr/include/python3.8
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-9lbcdnd7/onnx_1def4d4575e14ec3910a14f6ec2a2298/.setuptools-cmake-build
      [  1%] Running C++ protocol buffer compiler on /tmp/pip-install-9lbcdnd7/onnx_1def4d4575e14ec3910a14f6ec2a2298/.setuptools-cmake-build/onnx/onnx-ml.proto
      [  4%] Built target onnxifi_loader
      [  8%] Built target onnxifi_dummy
      [  9%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
      --python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
      gmake[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:74: onnx/onnx-ml.pb.cc] Error 1
      gmake[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/gen_onnx_proto.dir/all] Error 2
      gmake[1]: *** Waiting for unfinished jobs....
      [ 11%] Linking C shared module libonnxifi.so
      [ 11%] Built target onnxifi_wrapper
      gmake: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9lbcdnd7/onnx_1def4d4575e14ec3910a14f6ec2a2298/setup.py", line 315, in <module>
          setuptools.setup(
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-9lbcdnd7/onnx_1def4d4575e14ec3910a14f6ec2a2298/setup.py", line 209, in run
          self.run_command('cmake_build')
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/ai/venv/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-9lbcdnd7/onnx_1def4d4575e14ec3910a14f6ec2a2298/setup.py", line 203, in run
          subprocess.check_call(build_args)
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/ai/venv/rknn/bin/cmake', '--build', '.', '--', '-j', '128']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of onnx
  Moving to /home/ai/venv/rknn/bin/backend-test-tools
   from /tmp/pip-uninstall-ro4unz7a/backend-test-tools
  Moving to /home/ai/venv/rknn/bin/check-model
   from /tmp/pip-uninstall-ro4unz7a/check-model
  Moving to /home/ai/venv/rknn/bin/check-node
   from /tmp/pip-uninstall-ro4unz7a/check-node
  Moving to /home/ai/venv/rknn/lib/python3.8/site-packages/onnx-1.7.0.dist-info/
   from /home/ai/venv/rknn/lib/python3.8/site-packages/~nnx-1.7.0.dist-info
  Moving to /home/ai/venv/rknn/lib/python3.8/site-packages/onnx.libs/
   from /home/ai/venv/rknn/lib/python3.8/site-packages/~nnx.libs
  Moving to /home/ai/venv/rknn/lib/python3.8/site-packages/onnx/
   from /home/ai/venv/rknn/lib/python3.8/site-packages/~nnx
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> onnx
`

**Comment by CUBOXDev** [comment]
Did you solved this issue? I have same issue...
```shell
pip install ./rknn_toolkit-1.7.3-cp38-cp38-linux_x86_64.whl
```
```shell
Installing collected packages: onnx, matplotlib, flask, sklearn, rknn-toolkit
  Running setup.py install for onnx ... error
  error: subprocess-exited-with-error

  × Running setup.py install for onnx did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py:770: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running create_version
      running cmake_build
      Generated: /tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/.setuptools-cmake-build/onnx/onnx-ml.proto
      CMake Error at CMakeLists.txt:248 (message):
        Protobuf compiler not found
      Call Stack (most recent call first):
        CMakeLists.txt:279 (relative_protobuf_generate_cpp)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/setup.py", line 315, in <module>
          setuptools.setup(
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/setup.py", line 209, in run
          self.run_command('cmake_build')
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/setup.py", line 195, in run
          subprocess.check_call(cmake_args)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/brightro99/anaconda3/envs/rknn/include/python3.8', '-DPYTHON_EXECUTABLE=/home/brightro99/anaconda3/envs/rknn/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> onnx
```

**Comment by hrlee-cubox-ai** [comment]
Did you solved this issue? I have same issue...
```shell
pip install ./rknn_toolkit-1.7.3-cp38-cp38-linux_x86_64.whl
```
```shell
Installing collected packages: onnx, matplotlib, flask, sklearn, rknn-toolkit
  Running setup.py install for onnx ... error
  error: subprocess-exited-with-error

  × Running setup.py install for onnx did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py:770: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      /home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running create_version
      running cmake_build
      Generated: /tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/.setuptools-cmake-build/onnx/onnx-ml.proto
      CMake Error at CMakeLists.txt:248 (message):
        Protobuf compiler not found
      Call Stack (most recent call first):
        CMakeLists.txt:279 (relative_protobuf_generate_cpp)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/setup.py", line 315, in <module>
          setuptools.setup(
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/setup.py", line 209, in run
          self.run_command('cmake_build')
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f/setup.py", line 195, in run
          subprocess.check_call(cmake_args)
        File "/home/brightro99/anaconda3/envs/rknn/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/brightro99/anaconda3/envs/rknn/include/python3.8', '-DPYTHON_EXECUTABLE=/home/brightro99/anaconda3/envs/rknn/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-n9nhsl35/onnx_b0f63ba9ff26488284915b314560315f']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> onnx
```

**Comment by mechlya** [comment]
@Amanda-Qu  @hrlee-cubox-ai  Did you solved this error ?

**Comment by silaopi** [comment]
same error +1

**Comment by TrungLee2020** [comment]
I have same error  
`    ERROR: Command errored out with exit status 1:
     command: /home/trunglx/external/rknn-toolkit/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4qa5bit5/psutil_8aaaeb7cb1bc4d19a60da289be930aac/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4qa5bit5/psutil_8aaaeb7cb1bc4d19a60da289be930aac/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8bh4dbj1/install-record.txt --single-version-externally-managed --compile --install-headers /home/trunglx/external/rknn-toolkit/venv/include/site/python3.6/psutil
         cwd: /tmp/pip-install-4qa5bit5/psutil_8aaaeb7cb1bc4d19a60da289be930aac/
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
    creating build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=562 -DPSUTIL_LINUX=1 -I/home/trunglx/external/rknn-toolkit/venv/include -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
        9 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of psutil
  Moving to /home/trunglx/external/rknn-toolkit/venv/lib/python3.6/site-packages/psutil-5.9.4.dist-info/
   from /home/trunglx/external/rknn-toolkit/venv/lib/python3.6/site-packages/~sutil-5.9.4.dist-info
  Moving to /home/trunglx/external/rknn-toolkit/venv/lib/python3.6/site-packages/psutil/
   from /home/trunglx/external/rknn-toolkit/venv/lib/python3.6/site-packages/~sutil
ERROR: Command errored out with exit status 1: /home/trunglx/external/rknn-toolkit/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4qa5bit5/psutil_8aaaeb7cb1bc4d19a60da289be930aac/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4qa5bit5/psutil_8aaaeb7cb1bc4d19a60da289be930aac/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8bh4dbj1/install-record.txt --single-version-externally-managed --compile --install-headers /home/trunglx/external/rknn-toolkit/venv/include/site/python3.6/psutil Check the logs for full command output.
`

**Comment by liufangtao** [comment]
same error +1
