### ISSUE TITLE
tflite int8 model convert to rknn failed.

### ISSUE THREAD

**Issue by yichi-cui** [rockchip-linux/rknn-toolkit#342]
hi, we convert tflite to rknn ,but failed . log like below ,please to help to find root cause.

D Using CPPUTILS: False
I Start importing tflite...
I Model: meigetest-int8
I Version: 3
I Description: MLIR Converted.
I Subgraphs: 1
D import clients finished
D Convert layer quantize
D Convert layer mul
D Convert layer sub
D Convert layer conv_2d
E Catch exception when loading tflite model: ./meigetest-int8.tflite!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/lite/RKNN_map_op.py", line 148, in rknn.base.RKNNlib.converter.lite.RKNN_map_op._conv
E   File "rknn/base/RKNNlib/converter/lite/RKNN_map_op.py", line 13, in rknn.base.RKNNlib.converter.lite.RKNN_map_op._append_const_data
E   File "rknn/base/RKNNlib/converter/lite/RKNN_map_op.py", line 19, in rknn.base.RKNNlib.converter.lite.RKNN_map_op._append_const_tensor_ext
E   File "rknn/base/RKNNlib/converter/lite/utils.py", line 120, in rknn.base.RKNNlib.converter.lite.utils.get_buffer_from_tensor
E   File "rknn/base/RKNNlib/converter/lite/utils.py", line 85, in rknn.base.RKNNlib.converter.lite.utils.dequantize_buffer
E AssertionError
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by yichi-cui** [comment]
our tensorflow is 2.6 and we try to load xxx.int8.tflite model, then the error happen.
is the tensorflow new ,so can not work ? how can we solve the issue and keep the tensorflow version.
