### ISSUE TITLE
lstm to rknn failed

### ISSUE THREAD

**Issue by andrewhuman** [rockchip-linux/rknn-toolkit#356]
the network is:
![image](https://user-images.githubusercontent.com/34361699/227170047-d636c365-54bd-483c-9520-da4e079bee27.png)

convert:
![image](https://user-images.githubusercontent.com/34361699/227170340-7adff58e-7d90-4dcc-a4c7-f2419b95c65c.png)
error:
I End importing pytorch...
I Generate input meta ...
I Load input meta
I Generate input meta ...
D import clients finished
I Load net...
I Load data...
I Load input meta
D Process speech.1_0 ...
D RKNN output shape(input): (1 67 80)
D Tensor @speech.1_0:out0 type: float32
D Process reshape_at_x.1_3_1 ...
D RKNN output shape(reshape): (1 67 80)
D Tensor @reshape_at_x.1_3_1:out0 type: float32
D Process unsqueeze_at_input.3_4_2 ...
D RKNN output shape(reshape): (1 1 67 80)
D Tensor @unsqueeze_at_input.3_4_2:out0 type: float32
D Process convolution_at_input0.1_5_3_RKNN_mark_perm_32 ...
D RKNN output shape(permute): (1 67 80 1)
D Tensor @convolution_at_input0.1_5_3_RKNN_mark_perm_32:out0 type: float32
D Process convolution_at_input0.1_5_3 ...
D RKNN output shape(convolution): (1 33 39 32)
D Tensor @convolution_at_input0.1_5_3:out0 type: float32
D Process relu_at_48_6_4 ...
D RKNN output shape(relu): (1 33 39 32)
D Tensor @relu_at_48_6_4:out0 type: float32
D Process convolution_at_input.4_7_5 ...
D RKNN output shape(convolution): (1 16 19 32)
D Tensor @convolution_at_input.4_7_5:out0 type: float32
D Process relu_at_61_8_6 ...
D RKNN output shape(relu): (1 16 19 32)
D Tensor @relu_at_61_8_6:out0 type: float32
D Process permute_at_x0.1_9_7 ...
D RKNN output shape(permute): (1 16 32 19)
D Tensor @permute_at_x0.1_9_7:out0 type: float32
D Process reshape_at_input0.3_14_8 ...
D RKNN output shape(reshape): (1 16 608)
D Tensor @reshape_at_input0.3_14_8:out0 type: float32
D Process transpose_at_input.6_86_87_15_9 ...
D RKNN output shape(permute): (16 1 608)
D Tensor @transpose_at_input.6_86_87_15_9:out0 type: float32
D Process lstm_at_input.6_86_87_16_10 ...
D RKNN output shape(lstm): (16 1 1024) (1 1024) (1 1024)
D Tensor @lstm_at_input.6_86_87_16_10:out0 type: float32
D Tensor @lstm_at_input.6_86_87_16_10:out1 type: float32
D Tensor @lstm_at_input.6_86_87_16_10:out2 type: float32
D Process transpose_at_input.6_86_87_17_11 ...
D RKNN output shape(permute): (1 16 1024)
D Tensor @transpose_at_input.6_86_87_17_11:out0 type: float32
D Process layernormalize_at_input.8_16_12 ...
D RKNN output shape(layernormalize): (1 16 1024)
D Tensor @layernormalize_at_input.8_16_12:out0 type: float32
D Process transpose_at_input.10_109_110_17_13 ...
D RKNN output shape(permute): (16 1 1024)
D Tensor @transpose_at_input.10_109_110_17_13:out0 type: float32
D Process lstm_at_input.10_109_110_18_14 ...
D RKNN output shape(lstm): (16 1 1024) (1 1024) (1 1024)
D Tensor @lstm_at_input.10_109_110_18_14:out0 type: float32
D Tensor @lstm_at_input.10_109_110_18_14:out1 type: float32
D Tensor @lstm_at_input.10_109_110_18_14:out2 type: float32
D Process transpose_at_input.10_109_110_19_15 ...
D RKNN output shape(permute): (1 16 1024)
D Tensor @transpose_at_input.10_109_110_19_15:out0 type: float32
D Process layernormalize_at_input.12_18_16 ...
D RKNN output shape(layernormalize): (1 16 1024)
D Tensor @layernormalize_at_input.12_18_16:out0 type: float32
D Process transpose_at_input.14_132_133_19_17 ...
D RKNN output shape(permute): (16 1 1024)
D Tensor @transpose_at_input.14_132_133_19_17:out0 type: float32
D Process lstm_at_input.14_132_133_20_18 ...
D RKNN output shape(lstm): (16 1 1024) (1 1024) (1 1024)
D Tensor @lstm_at_input.14_132_133_20_18:out0 type: float32
D Tensor @lstm_at_input.14_132_133_20_18:out1 type: float32
D Tensor @lstm_at_input.14_132_133_20_18:out2 type: float32
D Process transpose_at_input.14_132_133_21_19 ...
D RKNN output shape(permute): (1 16 1024)
D Tensor @transpose_at_input.14_132_133_21_19:out0 type: float32
D Process layernormalize_at_input.16_20_20 ...
D RKNN output shape(layernormalize): (1 16 1024)
D Tensor @layernormalize_at_input.16_20_20:out0 type: float32
D Process transpose_at_input.18_155_156_21_21 ...
D RKNN output shape(permute): (16 1 1024)
D Tensor @transpose_at_input.18_155_156_21_21:out0 type: float32
D Process lstm_at_input.18_155_156_22_22 ...
D RKNN output shape(lstm): (16 1 1024) (1 1024) (1 1024)
D Tensor @lstm_at_input.18_155_156_22_22:out0 type: float32
D Tensor @lstm_at_input.18_155_156_22_22:out1 type: float32
D Tensor @lstm_at_input.18_155_156_22_22:out2 type: float32
D Process transpose_at_input.18_155_156_23_23 ...
D RKNN output shape(permute): (1 16 1024)
D Tensor @transpose_at_input.18_155_156_23_23:out0 type: float32
D Process layernormalize_at_input.20_22_24 ...
D RKNN output shape(layernormalize): (1 16 1024)
D Tensor @layernormalize_at_input.20_22_24:out0 type: float32
D Process transpose_at_input.2_178_179_23_25 ...
D RKNN output shape(permute): (16 1 1024)
D Tensor @transpose_at_input.2_178_179_23_25:out0 type: float32
D Process lstm_at_input.2_178_179_24_26 ...
D RKNN output shape(lstm): (16 1 1024) (1 1024) (1 1024)
D Tensor @lstm_at_input.2_178_179_24_26:out0 type: float32
D Tensor @lstm_at_input.2_178_179_24_26:out1 type: float32
D Tensor @lstm_at_input.2_178_179_24_26:out2 type: float32
D Process transpose_at_input.2_178_179_25_27 ...
D RKNN output shape(permute): (1 16 1024)
D Tensor @transpose_at_input.2_178_179_25_27:out0 type: float32
D Process layernormalize_at_input.5_24_28 ...
D RKNN output shape(layernormalize): (1 16 1024)
D Tensor @layernormalize_at_input.5_24_28:out0 type: float32
D Process linear_at_input.1_25_29 ...
D RKNN output shape(fullconnect): (1 3894)
D Tensor @linear_at_input.1_25_29:out0 type: float32
D Process softmax_at_193_26_30 ...
D RKNN output shape(softmax): (1 3894)
D Tensor @softmax_at_193_26_30:out0 type: float32
D Process attach_softmax_at_193_26_out0_31 ...
D RKNN output shape(output): (1 3894)
D Tensor @attach_softmax_at_193_26_out0_31:out0 type: float32
I Build lstm_3 complete.
I Initialzing network optimizer by /media/data1/3rdtool/miniconda3/envs/rknn_v1.7.1/lib/python3.6/site-packages/rknn/config/npu_config/PUMA ...
D Optimizing network with merge_ximum, qnt_adjust_coef, multiply_transform, add_extra_io, format_input_ops, auto_fill_zero_bias, conv_kernel_transform, twod_op_transform, strip_op, extend_unstack_split, merge_layer, transform_layer, broadcast_op, strip_op, auto_fill_reshape_zero, adjust_output_attrs, insert_dtype_converterf
D Strip layer reshape_at_x.1_3_1(reshape)
I Start T2C Switcher...
D Optimizing network with broadcast_op, t2c_fc
D insert permute permute_at_x0.1_9_7_RKNN_mark_perm_33 before permute_at_x0.1_9_7
D insert permute convolution_at_input0.1_5_3_RKNN_mark_perm_34 before convolution_at_input0.1_5_3
D remove permute convolution_at_input0.1_5_3_RKNN_mark_perm_32
D remove permute convolution_at_input0.1_5_3_RKNN_mark_perm_34
D remove permute permute_at_x0.1_9_7_RKNN_mark_perm_33
D Convert permute parameter [0 1 3 2] to [0, 2, 1, 3]
I End T2C Switcher...
D Optimizing network with merge_ximum, qnt_adjust_coef, multiply_transform, add_extra_io, format_input_ops, auto_fill_zero_bias, conv_kernel_transform, twod_op_transform, strip_op, extend_unstack_split, merge_layer, transform_layer, broadcast_op, strip_op, auto_fill_reshape_zero, adjust_output_attrs, insert_dtype_converter
D Optimizing network with conv_1xn_transform, proposal_opt, c2drv_convert_axis, c2drv_convert_shape, c2drv_convert_array, c2drv_cast_dtype, c2drv_trans_data
E Error convert axis: axis(2) > dim_num(1)
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/optimize/optimizer.py", line 355, in rknn.base.RKNNlib.optimize.optimizer.Optimizer.apply
E   File "rknn/base/RKNNlib/optimize/rules/c2drv/convert_axis.py", line 119, in rknn.base.RKNNlib.optimize.rules.c2drv.convert_axis.C2DRV_ConvertAxis.apply
E   File "rknn/base/RKNNlib/optimize/rules/c2drv/convert_axis.py", line 59, in rknn.base.RKNNlib.optimize.rules.c2drv.convert_axis._convert_softmax_axis
E   File "rknn/base/RKNNlib/optimize/rules/c2drv/utils.py", line 11, in rknn.base.RKNNlib.optimize.rules.c2drv.utils.c2drv_convert_axis
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Error convert axis: axis(2) > dim_num(1)
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by andrewhuman** [comment]
how can i do it?

**Comment by andrewhuman** [comment]
I test input_size_list=[[1, 67,80]]) #[[67,80,1]] #[[1,1,67,80]]。But the same error !
