### ISSUE TITLE
onnx加载模型失败 TypeError: '<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by OrliMH** [rockchip-linux/rknn-toolkit#357]
在使用rknn-toolkit2 （版本1.4.0），onnx 转 rknn的 加载模型这一步，加载不成功，报错信息如下，请问怎么解决？

W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
--> Loading model
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
E load_onnx: Catch exception when loading onnx model: /rknn_yolov5_demo/rvm_resnet50_fp32.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1152, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 617, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx: TypeError: '<=' not supported between instances of 'NoneType' and 'int'
load model failed!

**Comment by learn136** [comment]
see this:
https://github.com/rockchip-linux/rknn-toolkit2/issues/114
