### ISSUE TITLE
tf2.2下keras的h5模型lstm转rknn报错

### ISSUE THREAD

**Issue by hominwwww** [rockchip-linux/rknn-toolkit#361]
--> Config model
done
--> Loading model
2023-03-27 17:44:58.010276: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/homin/venv/lib/python3.6/site-packages/cv2/../../lib:
2023-03-27 17:44:58.010406: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/homin/venv/lib/python3.6/site-packages/cv2/../../lib:
2023-03-27 17:44:58.010500: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/homin/venv/lib/python3.6/site-packages/cv2/../../lib:
2023-03-27 17:44:58.010592: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/homin/venv/lib/python3.6/site-packages/cv2/../../lib:
2023-03-27 17:44:58.010683: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/homin/venv/lib/python3.6/site-packages/cv2/../../lib:
2023-03-27 17:44:58.010776: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/homin/venv/lib/python3.6/site-packages/cv2/../../lib:
2023-03-27 17:44:58.010869: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/homin/venv/lib/python3.6/site-packages/cv2/../../lib:
2023-03-27 17:44:58.010885: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
W:tensorflow:From /home/homin/venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm (LSTM)                  (None, 64)                2638080   
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
DENSE_1 (Dense)              (None, 128)               8320      
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
output (Dense)               (None, 5)                 645       
=================================================================
Total params: 2,647,045
Trainable params: 2,647,045
Non-trainable params: 0
_________________________________________________________________
E Catch exception when loading keras model: ./my_lstm_model.h5!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_keras.py", line 1035, in rknn.base.RKNNlib.converter.convert_keras.convert_keras.model_parser
E   File "rknn/base/RKNNlib/converter/convert_keras.py", line 762, in rknn.base.RKNNlib.converter.convert_keras.convert_keras.f_lstm
E   File "/home/homin/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 561, in __iter__
E     self._disallow_iteration()
E   File "/home/homin/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 557, in _disallow_iteration
E     self._disallow_in_graph_mode("iterating over `tf.Tensor`")
E   File "/home/homin/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 537, in _disallow_in_graph_mode
E     " this function with @tf.function.".format(task))
E tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by hominwwww** [comment]
模型如下：
def full_model(summary=False):
    print('building the model ... ')
    model = Sequential()

    model.add(LSTM(64, return_sequences=False, stateful=False,input_shape=(60, 10240)))
    model.add(Dropout(.5,name='dropout_1'))
    model.add(Dense(128, activation='relu', name='DENSE_1'))
    model.add(Dropout(.5,name='dropout_2'))
    model.add(Dense(5, activation='softmax', name = 'output'))

    return model

输入是 (None, 60, 10240)
