### ISSUE TITLE
rknn-toolkit将模型分发到NPU设备推理保存

### ISSUE THREAD

**Issue by w-yonglin** [rockchip-linux/rknn-toolkit#365]
PC使用adb线与rk3399pro连接，将test.py中的ret = rknn.init_runtime()改为ret = rknn.init_runtime(target='rk3399pro',device_id='56c0d97c7b4de727')。运行test.py时报以下错误。

--> Init runtime environment
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
E RKNNAPI: rknn_init,  driver open fail!  ret = -9(ERROR_PIPE)!
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 936, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
E Current device id is: 56c0d97c7b4de727
E Devices connected:
E ['56c0d97c7b4de727']
Init runtime environment failed

**Comment by twd19990423** [comment]
设备没有检索到 
sudo adb kill-server 
sudo adb start-server
adb devices

**Comment by w-yonglin** [comment]
在docker里面是可以检索到设备的
root@d96296b08a1e:~# adb devices
List of devices attached
56c0d97c7b4de727	device

test.py中改动了以下内容
ret = rknn.init_runtime(target='rk3399pro',device_id='56c0d97c7b4de727')
