### ISSUE TITLE
rknn.accuracy_analysis 报错

### ISSUE THREAD

**Issue by JunGenius** [rockchip-linux/rknn-toolkit#369]
你好, 作者.
想请教下，我使用 mmpose 模型 ，做精度分析时，报如下错误，是什么原因导致的 ？  非常感谢.

    2023-05-08 13:50:57.833593: W tensorflow/core/framework/op_kernel.cc:1490] Invalid argument: ValueError: Unknown element o
    Traceback (most recent call last):
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
        ret = func(*args)
      File "rknn/base/acuitylib/acuitynetbuilder.py", line 98, in rknn.base.acuitylib.acuitynetbuilder.draw_data_distribute
      File "rknn/base/acuitylib/acuitynetbuilder.py", line 59, in rknn.base.acuitylib.acuitynetbuilder.image_drawing
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2691, in legend
        return gca().legend(*args, **kwargs)
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 926, in gca
        return gcf().gca(**kwargs)
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1932, in gca
        return self.add_subplot(1, 1, 1, **kwargs)
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1416, in add_subplot
        return self._add_axes_internal(key, a)
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1420, in _add_axes_internal
        self._axstack.add(key, ax)
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 135, in add
        super().remove((key, a_existing))
      File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 743, in remove
        raise ValueError('Unknown element o')
    ValueError: Unknown element o
    
    I Save snapshot for layer: Resize_Resize_442_371
    E Catch exception when snapshot: InvalidArgumentError()
    E Traceback (most recent call last):
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    E     return fn(*args)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    E     options, feed_dict, fetch_list, target_list, run_metadata)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    E     run_metadata)
    E tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: Unknown element o
    E Traceback (most recent call last):
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    E     ret = func(*args)
    E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 98, in rknn.base.RKNNlib.RKNNnetbuilder.draw_data_distribute
    E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 53, in rknn.base.RKNNlib.RKNNnetbuilder.image_drawing
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2438, in bar
    E     return gca().bar(
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 926, in gca
    E     return gcf().gca(**kwargs)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1932, in gca
    E     return self.add_subplot(1, 1, 1, **kwargs)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1416, in add_subplot
    E     return self._add_axes_internal(key, a)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1420, in _add_axes_internal
    E     self._axstack.add(key, ax)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 135, in add
    E     super().remove((key, a_existing))
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 743, in remove
    E     raise ValueError('Unknown element o')
    E ValueError: Unknown element o
    E        [[{{node Add_Add_373_446/PyFunc_1}}]]
    E During handling of the above exception, another exception occurred:
    E Traceback (most recent call last):
    E   File "rknn/base/RKNNlib/RKNN_session.py", line 37, in rknn.base.RKNNlib.RKNN_session.RKNNSession.run
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    E     run_metadata_ptr)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    E     feed_dict_tensor, options, run_metadata)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    E     run_metadata)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    I Queue cancelled.
    E     raise type(e)(node_def, op, message)
    E tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: Unknown element o
    E Traceback (most recent call last):
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    E     ret = func(*args)
    E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 98, in rknn.base.RKNNlib.RKNNnetbuilder.draw_data_distribute
    E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 53, in rknn.base.RKNNlib.RKNNnetbuilder.image_drawing
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2438, in bar
    E     return gca().bar(
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 926, in gca
    E     return gcf().gca(**kwargs)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1932, in gca
    E     return self.add_subplot(1, 1, 1, **kwargs)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1416, in add_subplot
    E     return self._add_axes_internal(key, a)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 1420, in _add_axes_internal
    E     self._axstack.add(key, ax)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/figure.py", line 135, in add
    E     super().remove((key, a_existing))
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 743, in remove
    E     raise ValueError('Unknown element o')
    E ValueError: Unknown element o
    E        [[node Add_Add_373_446/PyFunc_1 (defined at /home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/rknn/api/rknn.py:347) ]]
    E Original stack trace for 'Add_Add_373_446/PyFunc_1':
    E   File "onnx_to_rknn.py", line 45, in <module>
    E     ret = rknn.accuracy_analysis(inputs='./images/dataset1.txt',output_dir="./output_dir", dump_file_type="tensor")
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/rknn/api/rknn.py", line 347, in accuracy_analysis
    E     draw_data_distribute=draw_data_distribute)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    E     return func(*args, **kwargs)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 480, in py_func
    E     return py_func_common(func, inp, Tout, stateful, name=name)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 462, in py_func_common
    E     func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 285, in _internal_py_func
    E     input=inp, token=token, Tout=Tout, name=name)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 159, in py_func
    E     "PyFunc", input=input, token=token, Tout=Tout, name=name)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    E     op_def=op_def)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    E     return func(*args, **kwargs)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    E     op_def=op_def)
    E   File "/home/qh/.conda/envs/rknnpy36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    E     self._traceback = tf_stack.extract_stack()
    E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
    E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by yangyuya** [comment]
您好，我遇到了同样的问题，请问解决了吗？

**Comment by huangqiu15444** [comment]
同问。
