### ISSUE TITLE
tensorflow2.2 QAT模型转换rknn报错

### ISSUE THREAD

**Issue by SWen1994** [rockchip-linux/rknn-toolkit#373]
您好！使用tensorflow2.2 QAT训练的模型，转换rknn报错
错误信息：
E Catch exception when loading tensorflow model: ./model_qat.pb!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 254, in rknn.api.rknn_base.RKNNBase.load_tensorflow
E   File "rknn/base/RKNNlib/RK_nn.py", line 51, in rknn.base.RKNNlib.RK_nn.RKnn.load_tensorflow
E   File "rknn/base/RKNNlib/app/importer/import_tensorflow.py", line 140, in rknn.base.RKNNlib.app.importer.import_tensorflow.Importensorflow.run
E TypeError: object of type 'NoneType' has no len()
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

log_feedback如下：
W Verbose file path is invalid, debug info will not dump to file.
D Using CPPUTILS: True
I Start importing tensorflow...
D import clients finished
I Current TF Model producer version 175 min consumer version 0 bad consumer version []
I short-cut sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp/resource:out0 - sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:in0 skip sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp
I short-cut sequential/quant_dense/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_dense/MovingAvgQuantize/FakeQuantWithMinMaxVars:in1 skip sequential/quant_dense/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_dense_2/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_dense_2/MovingAvgQuantize/FakeQuantWithMinMaxVars:in1 skip sequential/quant_dense_2/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_dense_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_dense_1/MovingAvgQuantize/FakeQuantWithMinMaxVars:in1 skip sequential/quant_dense_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_2/resource:out0 - sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars:in2 skip sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_2
I short-cut sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars:in1 skip sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_1/resource:out0 - sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:in1 skip sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_1
I short-cut sequential/quant_dense/BiasAdd/ReadVariableOp/resource:out0 - sequential/quant_dense/BiasAdd:in1 skip sequential/quant_dense/BiasAdd/ReadVariableOp
I short-cut sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars:in1 skip sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_dense_1/BiasAdd/ReadVariableOp/resource:out0 - sequential/quant_dense_1/BiasAdd:in1 skip sequential/quant_dense_1/BiasAdd/ReadVariableOp
I short-cut sequential/quant_dense_2/BiasAdd/ReadVariableOp/resource:out0 - sequential/quant_dense_2/BiasAdd:in1 skip sequential/quant_dense_2/BiasAdd/ReadVariableOp
I short-cut sequential/quant_dense_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_dense_1/MovingAvgQuantize/FakeQuantWithMinMaxVars:in2 skip sequential/quant_dense_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_2/resource:out0 - sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars:in2 skip sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_2
I short-cut sequential/quant_dense_2/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_dense_2/MovingAvgQuantize/FakeQuantWithMinMaxVars:in2 skip sequential/quant_dense_2/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_conv2d/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_conv2d/MovingAvgQuantize/FakeQuantWithMinMaxVars:in2 skip sequential/quant_conv2d/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_dense/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_dense/MovingAvgQuantize/FakeQuantWithMinMaxVars:in2 skip sequential/quant_dense/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_conv2d/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_conv2d/MovingAvgQuantize/FakeQuantWithMinMaxVars:in1 skip sequential/quant_conv2d/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars:in0 skip sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars:in1 skip sequential/quant_dense_1/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_2/resource:out0 - sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars:in2 skip sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp_2
I short-cut sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars:in0 skip sequential/quant_dense/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_dense_1/MovingAvgQuantize/FakeQuantWithMinMaxVars:out0 - sequential/quant_dense_2/MatMul:in0 skip sequential/quant_dropout/Identity
I short-cut sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_2/resource:out0 - sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:in2 skip sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_2
I short-cut sequential/quant_conv2d_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1/resource:out0 - sequential/quant_conv2d_1/MovingAvgQuantize/FakeQuantWithMinMaxVars:in2 skip sequential/quant_conv2d_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp_1
I short-cut sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars:in0 skip sequential/quant_dense_2/LastValueQuant/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_2/resource:out0 - sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:in2 skip sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_2
I short-cut sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_1/resource:out0 - sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:in1 skip sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp_1
I short-cut sequential/quant_conv2d_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp/resource:out0 - sequential/quant_conv2d_1/MovingAvgQuantize/FakeQuantWithMinMaxVars:in1 skip sequential/quant_conv2d_1/MovingAvgQuantize/FakeQuantWithMinMaxVars/ReadVariableOp
I short-cut sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp/resource:out0 - sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:in0 skip sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel/ReadVariableOp
I Have 2 tensors convert to const tensor
D Const tensors:
D ['sequential/quant_conv2d_1/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:out0', 'sequential/quant_conv2d/LastValueQuant/FakeQuantWithMinMaxVarsPerChannel:out0']
E Catch exception when loading tensorflow model: ./model_qat.pb!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 254, in rknn.api.rknn_base.RKNNBase.load_tensorflow
E   File "rknn/base/RKNNlib/RK_nn.py", line 51, in rknn.base.RKNNlib.RK_nn.RKnn.load_tensorflow
E   File "rknn/base/RKNNlib/app/importer/import_tensorflow.py", line 140, in rknn.base.RKNNlib.app.importer.import_tensorflow.Importensorflow.run
E TypeError: object of type 'NoneType' has no len()
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by SWen1994** [comment]
使用的是RKNN1.7.3工具，
qat模型来自于tensorflow官方qat例子， mnist数字识别网络
![image](https://github.com/rockchip-linux/rknn-toolkit/assets/85141470/57fcdc0d-3251-44c9-81e0-eb8da68a1900)
