### ISSUE TITLE
R50 caffe模型转换失败

### ISSUE THREAD

**Issue by SeaRecluse** [rockchip-linux/rknn-toolkit#378]
版本1.7.3，如果不启用预编译可以转换，但是加载时会段错误。启用预编译转换出错，以下是错误log:

```
...
D Packing PRelu_97_117 ...
D Generate fake input
D Compiling start...
D Compiling finished.
D Generate pre-compile model data start...
D Generate pre-compile model data finished.
E Generate nbg failed.
E Catch exception when direct build RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/ovxconfiggenerator.py", line 319, in rknn.base.ovxconfiggenerator.generate_vx_config_from_files
E   File "rknn/base/RKNNlib/app/exporter/ovxlib_case/casegenerator.py", line 682, in rknn.base.RKNNlib.app.exporter.ovxlib_case.casegenerator.CaseGenerator.generate
E   File "rknn/base/RKNNlib/app/exporter/ovxlib_case/casegenerator.py", line 633, in rknn.base.RKNNlib.app.exporter.ovxlib_case.casegenerator.CaseGenerator._gen_special_case
E   File "rknn/base/RKNNlib/app/exporter/ovxlib_case/casegenerator.py", line 598, in rknn.base.RKNNlib.app.exporter.ovxlib_case.casegenerator.CaseGenerator._gen_nb_file
E AttributeError: 'CaseGenerator' object has no attribute 'nbg_graph_file_path'
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 594, in rknn.api.rknn_base.RKNNBase.direct_build
E   File "rknn/api/rknn_base.py", line 479, in rknn.api.rknn_base.RKNNBase._build
E   File "rknn/base/ovxconfiggenerator.py", line 321, in rknn.base.ovxconfiggenerator.generate_vx_config_from_files
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Generate nbg failed.
E Please feedback the detailed log file <RKNN_toolkit.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
```

**Comment by SeaRecluse** [comment]
需要的话我可以上传一下模型文件，包含原始onnx以及caffe
