### ISSUE TITLE
Generate NBG Failed -- AttributeError: 'CaseGenerator' object has no attribute 'nbg_graph_file_path'

### ISSUE THREAD

**Issue by Spyderm4n** [rockchip-linux/rknn-toolkit#379]
There was no error occured during model compiling and quantization, but the toolkit throwed this 
` AttributeError: 'CaseGenerator' object has no attribute 'nbg_graph_file_path'` 
when generating NGB block. I'm not sure if it is due to an unsupported op. in the model, or a system environment problem? 
The model is attached below, could anyone give me some help with it please? Thanks a lot !!

[sample.zip](https://github.com/rockchip-linux/rknn-toolkit/files/11797005/sample.zip)

```
Version: rknn-toolkit-1.7.3-cp38
Sys: Ubuntu 20.04
Model: PicoDet--PaddleDetection
Pre-compile: On

Full Log:
--> Building model
D import clients finished
I Load net...
I Load data...
I Load quantization tensor table
D Optimizing network with Qlayer_merge
I Load input meta
D Process image_391 ...
D RKNN output shape(input): (1 416 416 3)
D Tensor @image_391:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.0_375 ...
D RKNN output shape(convolution): (1 208 208 24)
D Tensor @Conv_p2o.Conv.0_375:out0 type: asymmetric_affine
D Process Div_p2o.Div.0_371 ...
D RKNN output shape(hard_swish): (1 208 208 24)
D Tensor @Div_p2o.Div.0_371:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.1_369 ...
D RKNN output shape(convolution): (1 208 208 24)
D Tensor @Conv_p2o.Conv.1_369:out0 type: asymmetric_affine
D Process Div_p2o.Div.1_365 ...
D RKNN output shape(hard_swish): (1 208 208 24)
D Tensor @Div_p2o.Div.1_365:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.2_363 ...
D RKNN output shape(convolution): (1 208 208 48)
D Tensor @Conv_p2o.Conv.2_363:out0 type: asymmetric_affine
D Process Div_p2o.Div.2_359 ...
D RKNN output shape(hard_swish): (1 208 208 48)
D Tensor @Div_p2o.Div.2_359:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.3_357 ...
D RKNN output shape(convolution): (1 104 104 48)
D Tensor @Conv_p2o.Conv.3_357:out0 type: asymmetric_affine
D Process Div_p2o.Div.3_353 ...
D RKNN output shape(hard_swish): (1 104 104 48)
D Tensor @Div_p2o.Div.3_353:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.4_351 ...
D RKNN output shape(convolution): (1 104 104 96)
D Tensor @Conv_p2o.Conv.4_351:out0 type: asymmetric_affine
D Process Div_p2o.Div.4_347 ...
D RKNN output shape(hard_swish): (1 104 104 96)
D Tensor @Div_p2o.Div.4_347:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.5_345 ...
D RKNN output shape(convolution): (1 104 104 96)
D Tensor @Conv_p2o.Conv.5_345:out0 type: asymmetric_affine
D Process Div_p2o.Div.5_342 ...
D RKNN output shape(hard_swish): (1 104 104 96)
D Tensor @Div_p2o.Div.5_342:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.6_341 ...
D RKNN output shape(convolution): (1 104 104 96)
D Tensor @Conv_p2o.Conv.6_341:out0 type: asymmetric_affine
D Process Div_p2o.Div.6_337 ...
D RKNN output shape(hard_swish): (1 104 104 96)
D Tensor @Div_p2o.Div.6_337:out0 type: asymmetric_affine
D Process Conv_p2o.Conv.7_336 ...
D RKNN output shape(convolution): (1 52 52 96)
D Tensor @Conv_p2o.Conv.7_336:out0 type: asymmetric_affine
D Process Div_p2o.Div.7_328 ...
D RKNN output shape(hard_swish): (1 52 52 96)
... (Too long, no error here)
D Tensor @Reshape_p2o.Reshape.41_7_RKNN_mark_perm_395:out0 type: float32
D Process Reshape_p2o.Reshape.41_7 ...
D RKNN output shape(reshape): (1 1 49)
D Tensor @Reshape_p2o.Reshape.41_7:out0 type: float32
D Process Concat_p2o.Concat.8_2 ...
D RKNN output shape(concat): (1 1 3598)
D Tensor @Concat_p2o.Concat.8_2:out0 type: float32
D Process attach_Concat_p2o.Concat.8/out0_1 ...
D RKNN output shape(output): (1 1 3598)
D Tensor @attach_Concat_p2o.Concat.8/out0_1:out0 type: float32
I Build Model from PaddlePaddle. complete.
I Initialzing network optimizer by /home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/config/npu_config/LION ...
D Optimizing network with merge_ximum, qnt_adjust_coef, multiply_transform, add_extra_io, format_input_ops, auto_fill_zero_bias, conv_kernel_transform, twod_op_transform, strip_op, extend_unstack_split, merge_layer, transform_layer, broadcast_op, strip_op, auto_fill_reshape_zero, adjust_output_attrs, insert_dtype_converter
I Conv_p2o.Conv.24_334 merged relu nexted.
I Conv_p2o.Conv.28_297 merged relu nexted.
I Start T2C Switcher...
D Optimizing network with broadcast_op, t2c_fc
D convert Concat_p2o.Concat.0_318(concat) axis 3 to 1
D convert Concat_p2o.Concat.2_264(concat) axis 3 to 1
D convert Concat_p2o.Concat.4_261(concat) axis 3 to 1
D convert Concat_p2o.Concat.6_267(concat) axis 3 to 1
D convert Mul_p2o.Mul.128_70(multiply) axis 3 to 1
D convert Mul_p2o.Mul.134_16(multiply) axis 3 to 1
D convert Mul_p2o.Mul.152_73(multiply) axis 3 to 1
D convert Mul_p2o.Mul.158_17(multiply) axis 3 to 1
D convert Mul_p2o.Mul.176_76(multiply) axis 3 to 1
D convert Mul_p2o.Mul.182_18(multiply) axis 3 to 1
D convert Mul_p2o.Mul.200_79(multiply) axis 3 to 1
D convert Mul_p2o.Mul.206_19(multiply) axis 3 to 1
D convert Mul_p2o.Mul.54_278(multiply) axis 3 to 1
D convert Mul_p2o.Mul.48_310(multiply) axis 3 to 1
D insert permute Reshape_p2o.Reshape.14_4_RKNN_mark_perm_392_RKNN_mark_perm_34 before Reshape_p2o.Reshape.14_4_RKNN_mark_perm_392
D insert permute Reshape_p2o.Reshape.23_5_RKNN_mark_perm_393_RKNN_mark_perm_36 before Reshape_p2o.Reshape.23_5_RKNN_mark_perm_393
D insert permute Reshape_p2o.Reshape.32_6_RKNN_mark_perm_394_RKNN_mark_perm_38 before Reshape_p2o.Reshape.32_6_RKNN_mark_perm_394
D insert permute Reshape_p2o.Reshape.41_7_RKNN_mark_perm_395_RKNN_mark_perm_40 before Reshape_p2o.Reshape.41_7_RKNN_mark_perm_395
D insert permute Reshape_p2o.Reshape.15_102_RKNN_mark_perm_54 before Reshape_p2o.Reshape.15_102
D insert permute Reshape_p2o.Reshape.24_103_RKNN_mark_perm_57 before Reshape_p2o.Reshape.24_103
D insert permute Reshape_p2o.Reshape.33_104_RKNN_mark_perm_60 before Reshape_p2o.Reshape.33_104
D insert permute Reshape_p2o.Reshape.42_105_RKNN_mark_perm_63 before Reshape_p2o.Reshape.42_105
D insert permute HardSigmoid_p2o.HardSigmoid.1_279_RKNN_mark_perm_401_RKNN_mark_perm_71 before HardSigmoid_p2o.HardSigmoid.1_279_RKNN_mark_perm_401
D insert permute HardSigmoid_p2o.HardSigmoid.0_316_RKNN_mark_perm_403_RKNN_mark_perm_74 before HardSigmoid_p2o.HardSigmoid.0_316_RKNN_mark_perm_403
D insert permute Mul_p2o.Mul.54_278_RKNN_mark_perm_77 before Mul_p2o.Mul.54_278
D insert permute Mul_p2o.Mul.48_310_RKNN_mark_perm_80 before Mul_p2o.Mul.48_310
D remove permute HardSigmoid_p2o.HardSigmoid.0_316_RKNN_mark_perm_403_RKNN_mark_perm_74
D remove permute HardSigmoid_p2o.HardSigmoid.0_316_RKNN_mark_perm_403
D remove permute Mul_p2o.Mul.48_310_RKNN_mark_perm_402
D remove permute Mul_p2o.Mul.48_310_RKNN_mark_perm_80
D remove permute HardSigmoid_p2o.HardSigmoid.1_279_RKNN_mark_perm_401_RKNN_mark_perm_71
D remove permute HardSigmoid_p2o.HardSigmoid.1_279_RKNN_mark_perm_401
D remove permute Mul_p2o.Mul.54_278_RKNN_mark_perm_400
D remove permute Mul_p2o.Mul.54_278_RKNN_mark_perm_77
D remove permute Reshape_p2o.Reshape.14_4_RKNN_mark_perm_392_RKNN_mark_perm_34
D remove permute Reshape_p2o.Reshape.14_4_RKNN_mark_perm_392
D remove permute Reshape_p2o.Reshape.23_5_RKNN_mark_perm_393_RKNN_mark_perm_36
D remove permute Reshape_p2o.Reshape.23_5_RKNN_mark_perm_393
D remove permute Reshape_p2o.Reshape.32_6_RKNN_mark_perm_394_RKNN_mark_perm_38
D remove permute Reshape_p2o.Reshape.32_6_RKNN_mark_perm_394
D remove permute Reshape_p2o.Reshape.41_7_RKNN_mark_perm_395_RKNN_mark_perm_40
D remove permute Reshape_p2o.Reshape.41_7_RKNN_mark_perm_395
I End T2C Switcher...
D Optimizing network with merge_ximum, qnt_adjust_coef, multiply_transform, add_extra_io, format_input_ops, auto_fill_zero_bias, conv_kernel_transform, twod_op_transform, strip_op, extend_unstack_split, merge_layer, transform_layer, broadcast_op, strip_op, auto_fill_reshape_zero, adjust_output_attrs, insert_dtype_converter
I Conv_p2o.Conv.24_334 merged relu nexted.
I Conv_p2o.Conv.28_297 merged relu nexted.
D Optimizing network with conv_1xn_transform, proposal_opt, c2drv_convert_axis, c2drv_convert_shape, c2drv_convert_array, c2drv_cast_dtype, c2drv_trans_data
I Building data ...
D /home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION

D /home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/lib/x64_linux:/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/lib/x64_linux/RKm

I Packing data ...
D Packing Conv_p2o.Conv.0_375 ...
D Quantize @Conv_p2o.Conv.0_375:bias to asymmetric_affine.
D Quantize @Conv_p2o.Conv.0_375:weight to asymmetric_affine.
D Packing Conv_p2o.Conv.100_209 ...
... (again too long no eror)
D Packing Conv_p2o.Conv.98_78 ...
D Quantize @Conv_p2o.Conv.98_78:bias to asymmetric_affine.
D Quantize @Conv_p2o.Conv.98_78:weight to asymmetric_affine.
D Packing Conv_p2o.Conv.99_47 ...
D Quantize @Conv_p2o.Conv.99_47:bias to asymmetric_affine.
D Quantize @Conv_p2o.Conv.99_47:weight to asymmetric_affine.
D Packing Conv_p2o.Conv.9_312 ...
D Quantize @Conv_p2o.Conv.9_312:bias to asymmetric_affine.
D Quantize @Conv_p2o.Conv.9_312:weight to asymmetric_affine.
D Packing Initializer_eager_tmp_0_21 ...
D Packing Initializer_eager_tmp_0_cp1_22 ...
D Packing Initializer_eager_tmp_1_9 ...
D Quantize @Initializer_eager_tmp_1_9:data to asymmetric_affine.
D Packing Initializer_eager_tmp_4_83 ...
D Quantize @Initializer_eager_tmp_4_83:data to asymmetric_affine.
D Packing Initializer_eager_tmp_4_cp1_85 ...
D Quantize @Initializer_eager_tmp_4_cp1_85:data to asymmetric_affine.
D Packing Initializer_eager_tmp_4_cp2_87 ...
D Quantize @Initializer_eager_tmp_4_cp2_87:data to asymmetric_affine.
D Packing Initializer_eager_tmp_4_cp3_89 ...
D Quantize @Initializer_eager_tmp_4_cp3_89:data to asymmetric_affine.
D Packing Initializer_p2o.helper.constant.408_32 ...
D Quantize @Initializer_p2o.helper.constant.408_32:data to asymmetric_affine.
D Generate fake input
D Compiling start...
D gcc -Wall -std=c++0x -I. -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/CL -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/VX -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ovxlib -D__linux__ -DLINUX -O3 -c rknn_pre_process.c
D gcc -Wall -std=c++0x -I. -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/CL -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/VX -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ovxlib -D__linux__ -DLINUX -O3 -c main.c
D gcc -Wall -std=c++0x -I. -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/CL -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/VX -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ovxlib -D__linux__ -DLINUX -O3 -c rknn_post_process.c
D gcc -Wall -std=c++0x -I. -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/CL -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/VX -I/home/xxx/anaconda3/envs/rk/lib/python3.8/site-packages/rknn/simulator/LION/include/ovxlib -D__linux__ -DLINUX -O3 -c rknn_modelfrompaddlepaddle.c
D Compiling finished.
D Generate pre-compile model data start...
D Generate pre-compile model data finished.
E Generate nbg failed.
E Catch exception when direct build RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/ovxconfiggenerator.py", line 319, in rknn.base.ovxconfiggenerator.generate_vx_config_from_files
E   File "rknn/base/RKNNlib/app/exporter/ovxlib_case/casegenerator.py", line 682, in rknn.base.RKNNlib.app.exporter.ovxlib_case.casegenerator.CaseGenerator.generate
E   File "rknn/base/RKNNlib/app/exporter/ovxlib_case/casegenerator.py", line 633, in rknn.base.RKNNlib.app.exporter.ovxlib_case.casegenerator.CaseGenerator._gen_special_case
E   File "rknn/base/RKNNlib/app/exporter/ovxlib_case/casegenerator.py", line 598, in rknn.base.RKNNlib.app.exporter.ovxlib_case.casegenerator.CaseGenerator._gen_nb_file
E AttributeError: 'CaseGenerator' object has no attribute 'nbg_graph_file_path'
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 594, in rknn.api.rknn_base.RKNNBase.direct_build
E   File "rknn/api/rknn_base.py", line 479, in rknn.api.rknn_base.RKNNBase._build
E   File "rknn/base/ovxconfiggenerator.py", line 321, in rknn.base.ovxconfiggenerator.generate_vx_config_from_files
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Generate nbg failed.
E Please feedback the detailed log file <RKNN_toolkit.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
```

**Comment by ZhuXiang-tuxing** [comment]
Hello, have you solved this problem? I have also encountered a similar error here and would like to ask you how to handle this issue.
