### ISSUE TITLE
转ONNX报错：W Not match tensor Slice_Slice_4399:out0  E Try match layer: Slice_Slice_4399:out0 failed!

### ISSUE THREAD

**Issue by AnthonyChanMarvel** [rockchip-linux/rknn-toolkit#381]
按照RKNN_OP_Support_And_Limit.xlsx中的测试版本配置的环境，RKNN-Toolkit 1.7.3、Pytorch 1.10.0、ONNX opset-verison 12

转换ERROR如下：

W Call onnx.optimizer.optimize fail, skip optimize
1.6.0
--> Config model
done
--> Loading model
/home/chenchen/anaconda3/envs/rknn/lib/python3.6/site-packages/rknn/api/rknn.py:150: RuntimeWarning: overflow encountered in exp
  ret = self.rknn_base.load_onnx(model, inputs, input_size_list, outputs)
W Not match tensor Slice_Slice_4399:out0 
E Try match layer: Slice_Slice_4399:out0 failed!
The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Catch exception when loading onnx model: /home/chenchen/projects/AllExperimentResults/InterHandSingle/onnx/InterHandSingle_exp75_1153.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1837, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1716, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 315, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 145, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 129, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1845, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match layer: Slice_Slice_4399:out0 failed!
E The OP of this layer may not yet support, please check document <RKNN_OP_Support.md>!
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

表格中明确写的加载ONNX模型支持split和slice操作的，请问这种情况怎么解决？

**Comment by jun214384468** [comment]
> 格中明确写的加载ONNX模型支持split和slice操作的，请问这种情况怎么解决？

最后是不是把split算子给取替换了
