### ISSUE TITLE
在使用rknn=1.6.0，load_onnx模型转换时，选用“mmse”的量化方式时，会包下面的错误。使用“normal”的方式是正常的。跪求解答。

### ISSUE THREAD

**Issue by yukaizhou** [rockchip-linux/rknn-toolkit#392]
D Real output shape: (2, 4, 4, 1792)
I Build torch-jit-export complete.
I Clean.
MMSE Quant Step 0:  96%|████████████████████████████████████████▏ | 316/330 [00:30<00:01,  8.51it/s]D Init sub net for ['Mul_Mul_350_10']
D import clients finished
I Mul_Mul_350_100@Conv_Conv_348_13:out0
I Mul_Mul_350_101@Initializer_1170_14:out0
E Can not find preprocess parameters for Initializer_1170_14.
W ----------------Warning(9)----------------
MMSE Quant Step 0:  96%|████████████████████████████████████████▎ | 317/330 [00:30<00:01, 10.26it/s]
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 592, in rknn.api.rknn_base.RKNNBase.build
E   File "rknn/api/rknn_base.py", line 1490, in rknn.api.rknn_base.RKNNBase._quantize2
E   File "rknn/base/RKNNlib/RK_nn.py", line 553, in rknn.base.RKNNlib.RK_nn.RKnn.quantize
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 145, in rknn.base.RKNNlib.app.medusa.quantization.Quantization.run
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 63, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._run_quantization
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 430, in rknn.base.RKNNlib.app.medusa.workspace.Workspace.run
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 288, in rknn.base.RKNNlib.app.medusa.workspace.Workspace._mmse_init_sub_net
E   File "rknn/api/rknn_log.py", line 312, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Can not find preprocess parameters for Initializer_1170_14.

**Comment by eRaul** [comment]
RKNN Toolkit已经更新到1.7.5了，里面有解一些MMSE的bug，可以更新工具后再试下。

**Comment by Liys0558** [comment]
RKNN Toolkit已经更新到1.7.5，选用“mmse”的量化方式时，会出现以下错误
`MMSE Quant Step 0:   0%|                                                    | 0/269 [00:00<?, ?it/s]E Run sub net (layer: Conv_/model.0/conv/Conv_358) catch exception: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[595,64,320,320] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node Conv_/model.0/conv/Conv_358_2/Conv2D (defined at /data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/rknn/api/rknn.py:291) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Conv_/model.0/conv/Conv_358_2/Add/_7]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[595,64,320,320] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node Conv_/model.0/conv/Conv_358_2/Conv2D (defined at /data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/rknn/api/rknn.py:291) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'Conv_/model.0/conv/Conv_358_2/Conv2D':
  File "convert.py", line 35, in <module>
    ret = rknn.build(do_quantization=do_quant, dataset=DATASET_PATH, pre_compile=False)
  File "/data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/rknn/api/rknn.py", line 291, in build
    batch_size=rknn_batch_size)
  File "/data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2014, in conv2d
    name=name)
  File "/data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/data/miniconda3/envs/rknn1.7.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

MMSE Quant Step 0:   0%|▏                                      | 1/269 [18:45<83:46:30, 1125.34s/it]
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 153, in rknn.base.RKNNlib.app.medusa.quantization.Quantization.run
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 62, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._run_quantization
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 987, in rknn.base.RKNNlib.app.medusa.workspace.Workspace.sparse_run
E   File "rknn/base/RKNNlib/app/medusa/workspace.py", line 592, in rknn.base.RKNNlib.app.medusa.workspace.Workspace._mmse_fine_tune_layers
E   File "rknn/base/RKNNlib/quantization/mmse_method.py", line 339, in rknn.base.RKNNlib.quantization.mmse_method.mmse_record_outputs
E TypeError: 'NoneType' object is not subscriptable
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Build model failed!
`

**Comment by Liys0558** [comment]
> RKNN Toolkit已经更新到1.7.5了，里面有解一些MMSE的bug，可以更新工具后再试下。

RKNN Toolkit已经更新到1.7.5，还是会报错，normal模式就没问题
