### ISSUE TITLE
PyTorch的QAT模型转换失败

### ISSUE THREAD

**Issue by yoyokitartora** [rockchip-linux/rknn-toolkit#396]
PyTorch 版本：1.10.0
rknn-toolkit 版本：v1.7.1和v1.7.5

使用PyTorch做QAT训练，QAT模型trace之后做转换，报错信息是：
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RK_nn.py", line 167, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 131, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 5245, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 5353, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
E   File "rknn/base/RKNNlib/converter/pytorch_util.py", line 543, in rknn.base.RKNNlib.converter.pytorch_util.get_weight_quant_params
E AssertionError
E Please feedback the detailed log file <log.txt> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

尝试使用v1.7.1和v1.7.5的rknn-toolkit，报错信息是一样的。

请问这可能是什么问题呢，要怎么解决？

**Comment by yu9s** [comment]
> PyTorch 版本：1.10.0 rknn-toolkit 版本：v1.7.1和v1.7.5
> 
> 使用PyTorch做QAT训练，QAT模型trace之后做转换，报错信息是： E Traceback (most recent call last): E File "rknn/base/RKNNlib/RK_nn.py", line 167, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch E File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 131, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run E File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 5245, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load E File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 5353, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets E File "rknn/base/RKNNlib/converter/pytorch_util.py", line 543, in rknn.base.RKNNlib.converter.pytorch_util.get_weight_quant_params E AssertionError E Please feedback the detailed log file <log.txt> to the RKNN Toolkit development team. E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
> 
> 尝试使用v1.7.1和v1.7.5的rknn-toolkit，报错信息是一样的。
> 
> 请问这可能是什么问题呢，要怎么解决？

请问qat之后，精度损失有降低吗？
