### ISSUE TITLE
针对yolov8s模型做量化精度分析，在accuracy_analysis接口中报错

### ISSUE THREAD

**Issue by rzzhangtao** [rockchip-linux/rknn-toolkit#409]
E Catch exception when snapshot: InvalidArgumentError()
I Queue cancelled.
E Traceback (most recent call last):
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
E     return fn(*args)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in _run_fn
E     return self._call_tf_sessionrun(options, feed_dict, fetch_list,
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in _call_tf_sessionrun
E     return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
E tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: Given element not contained in the stack
E Traceback (most recent call last):
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
E     ret = func(*args)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
E     return func(*args, **kwargs)
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 139, in rknn.base.RKNNlib.RKNNnetbuilder.draw_data_distribute
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 100, in rknn.base.RKNNlib.RKNNnetbuilder.image_drawing
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2738, in legend
E     return gca().legend(*args, **kwargs)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2368, in gca
E     return gcf().gca(**kwargs)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 2065, in gca
E     return self.add_subplot(1, 1, 1, **kwargs)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 1404, in add_subplot
E     return self._add_axes_internal(key, ax)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 1408, in _add_axes_internal
E     self._axstack.add(key, ax)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 125, in add
E     super().remove((key, a_existing))
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 643, in remove
E     raise ValueError('Given element not contained in the stack')
E ValueError: Given element not contained in the stack
E 	 [[{{node Initializer_onnx//Mul_424_5_1/PyFunc_1}}]]
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RKNN_session.py", line 37, in rknn.base.RKNNlib.RKNN_session.RKNNSession.run
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 957, in run
E     result = self._run(None, fetches, feed_dict, options_ptr,
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1180, in _run
E     results = self._do_run(handle, final_targets, final_fetches,
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _do_run
E     return self._do_call(_run_fn, feeds, fetches, targets, options,
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
E     raise type(e)(node_def, op, message)
E tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: Given element not contained in the stack
E Traceback (most recent call last):
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
E     ret = func(*args)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
E     return func(*args, **kwargs)
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 139, in rknn.base.RKNNlib.RKNNnetbuilder.draw_data_distribute
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 100, in rknn.base.RKNNlib.RKNNnetbuilder.image_drawing
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2738, in legend
E     return gca().legend(*args, **kwargs)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2368, in gca
E     return gcf().gca(**kwargs)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 2065, in gca
E     return self.add_subplot(1, 1, 1, **kwargs)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 1404, in add_subplot
E     return self._add_axes_internal(key, ax)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 1408, in _add_axes_internal
E     self._axstack.add(key, ax)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 125, in add
E     super().remove((key, a_existing))
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 643, in remove
E     raise ValueError('Given element not contained in the stack')
E ValueError: Given element not contained in the stack
E 	 [[node Initializer_onnx//Mul_424_5_1/PyFunc_1 (defined at /mnt/e/code/venv/lib/python3.8/site-packages/rknn/api/rknn.py:366) ]]
E Original stack trace for 'Initializer_onnx//Mul_424_5_1/PyFunc_1':
E   File "2-convert_tool.py", line 72, in <module>
E     rknn.accuracy_analysis(inputs='single_img.txt', target=target)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/rknn/api/rknn.py", line 366, in accuracy_analysis
E     ret = self.rknn_base.accuracy_analysis(inputs, output_dir, calc_qnt_error, target, device_id, dump_file_type,
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
E     return func(*args, **kwargs)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 555, in py_func
E     return py_func_common(func, inp, Tout, stateful, name=name)
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 536, in py_func_common
E     return _internal_py_func(
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 344, in _internal_py_func
E     result = gen_script_ops.py_func(
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_script_ops.py", line 148, in py_func
E     _, _, _op, _outputs = _op_def_library._apply_op_helper(
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
E     op = g._create_op_internal(op_type_name, inputs, dtypes=None,
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3319, in _create_op_internal
E     ret = Operation(
E   File "/mnt/e/code/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
E     self._traceback = tf_stack.extract_stack()
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by eRaul** [comment]
完整的log_feedback_to_the_rknn_toolkit_dev_team.log文件和所用的toolkit版本信息提供下？
