### ISSUE TITLE
toolkit转换yolov5s模型报错

### ISSUE THREAD

**Issue by zhishao** [rockchip-linux/rknn-toolkit#43]
![image](https://user-images.githubusercontent.com/18610954/104434977-d88df680-55c6-11eb-8d97-b431de2a37d5.png)
I Try match LeakyRelu_LeakyRelu_171:out0
I Match r_leakrelu [['LeakyRelu_LeakyRelu_171']] [['LeakyRelu']] to [['leakyrelu']]
I Try match LeakyRelu_LeakyRelu_153:out0
I Match r_leakrelu [['LeakyRelu_LeakyRelu_153']] [['LeakyRelu']] to [['leakyrelu']]
I Try match Conv_Conv_161:out0
I Match r_conv [['Conv_Conv_161', 'Initializer_model.17.m.0.cv2.conv.weight', 'Initializer_model.17.m.0.cv2.conv.bias']] [['Conv', 'Constant_0', 'Constant_1']] to [['convolution']]
I Try match Resize_Resize_155:out0
W Not match tensor Resize_Resize_155:out0 
E Try match Resize_Resize_155:out0 failed, catch exception!
W ----------------Warning(4)----------------
E Catch exception when loading onnx model: ./yolov5s.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 826, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 728, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 264, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 135, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 121, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 832, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/api/rknn_log.py", line 312, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match Resize_Resize_155:out0 failed, catch exception!
Load model failed!

模型中的位置
![image](https://user-images.githubusercontent.com/18610954/104435616-8ac5be00-55c7-11eb-8ac3-8789da0e2f38.png)
![image](https://user-images.githubusercontent.com/18610954/104435693-a204ab80-55c7-11eb-90a8-f238feecb53f.png)

看代码大概是位于模型中的上采样位置，pytorch中的操作是nn.Upsample。

**Comment by Jayyyyyyyyyyyy** [comment]
相同的问题，老哥解决了吗
