### ISSUE TITLE
Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID`

### ISSUE THREAD

**Issue by cv-on-device** [rockchip-linux/rknn-toolkit#443]
Hi, I run python test.py, occur error in `ret = rknn.init_runtime(target='rv1126', device_id='************')`
log follow:
`D Start adb...
D Connect to Device success!
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 936, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID`

**Comment by kingzcheung** [comment]
same error with me.
E RKNNAPI: RKNN VERSION:
E RKNNAPI:   API: 1.7.5 (bb79b30 build: 2023-06-20 09:54:19)
E RKNNAPI:   DRV: 1.7.5 (bb79b30 build: 2023-07-18 10:53:10)
E RKNNAPI: ==============================================
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 1008, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 340, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
E Current device id is: None
E Devices connected:
E ['b9467c6be2237e7a']

**Comment by yaowen-liu** [comment]
> 我也遇到了同样的错误。E RKNNAPI：RKNN 版本： E RKNNAPI：API：1.7.5（bb79b30 构建：2023-06-20 09:54:19） E RKNNAPI：DRV：1.7.5（bb79b30 构建：2023-07-18 10:53:10） E RKNNAPI：======================================================== E 初始化运行时捕获异常！ E Traceback (最近一次调用最后一次): E File "rknn/api/rknn_base.py", line 1008, in rknn.api.rknn_base.RKNNBase.init_runtime E File "rknn/api/rknn_runtime.py", line 340, in rknn.api.rknn_runtime.RKNNRuntime.build_graph E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID E 请将详细日志文件 <log_feedback_to_the_rknn_toolkit_dev_team.log> 反馈给 RKNN Toolkit 开发团队。 E 您也可以查看 github issues: https://github.com/rockchip-linux/rknn-toolkit/issues E Current device id is: None E Devices Connected: E ['b9467c6be2237e7a']

你好，我也遇到了同样的错误，请问最后解决了吗
