### ISSUE TITLE
rv1126 模型转换时，报RKNN_ERR_DEVICE_UNAVAILABLE

### ISSUE THREAD

**Issue by tony3805** [rockchip-linux/rknn-toolkit#450]
done
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
E RKNNAPI: rknn_init,  driver open fail!  ret = -9(ERROR_PIPE)!
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 1008, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 340, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
E Current device id is: None
E Devices connected:
E ['94f753164d73058c']
init runtime environment failed

根据Rockchip_Trouble_Shooting_RKNN_Toolkit_V1.7.5_CN.pdf 文档 第8.8节 提示
检查了
1.版本都是1.7.5
2.adb devices 可以查到设备
3.init_runtime()的 target 和 device_id 设置正确  这条不需要填写
4.npu_transfer_proxy 没有这个进程
5.安装驱动是puma版本不是mini

现在排查了，实在不知道什么原因。模型脚本，在另一台rv1126上已验证正常转换的。

**Comment by Eliza-and-black** [comment]
Did you solve this problem?
