### ISSUE TITLE
跑rknn-lite官方示例失败

### ISSUE THREAD

**Issue by lzzzzz14** [rockchip-linux/rknn-toolkit#453]
linaro@138V001000212263:~/Desktop/rknn-toolkit/rknn-toolkit-lite/examples/inference_with_lite$ python test.py
--> Load RKNN model
done
--> Init runtime environment
I RKNN: [13:32:31.065] RKNN Runtime Information: librknnrt version: 1.5.0 (e6fe0c678@2023-05-25T08:09:20)
I RKNN: [13:32:31.067] RKNN Driver Information: version: 0.9.0
E RKNN: [13:32:31.073] Invalid RKNN format
E RKNN: [13:32:31.073] rknn_init, load model failed!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/linaro/miniconda/envs/lz39/lib/python3.9/site-packages/rknnlite/api/rknn_lite.py", line 156, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 807, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID

Init runtime environment failed

环境为：
Package           Version
----------------- --------
numpy             1.26.4
opencv-python     4.9.0.80
pip               24.0
psutil            5.9.8
rknn-toolkit-lite 1.7.5
ruamel.yaml       0.18.6
ruamel.yaml.clib  0.2.8
setuptools        69.5.1
wheel             0.43.0

**Comment by lzzzzz14** [comment]
在aarch63平台，debian系统
