### ISSUE TITLE
Init runtime environment failed

### ISSUE THREAD

**Issue by moyu026** [rockchip-linux/rknn-toolkit#454]
代码是rknn-toolkit-lite2/examples/resnet18/test.py
https://github.com/airockchip/rknn-toolkit2/blob/77b71094e08391c543d9c65fea5f7cf98cc16eee/rknn-toolkit-lite2/examples/resnet18/test.py#L10

报错：
--> Load RKNN model
done
--> Init runtime environment
E RKNN: [03:28:11.710] failed to open rknpu module, need to insmod rknpu dirver!
E RKNN: [03:28:11.711] failed to open rknn device!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/uavai/.local/lib/python3.8/site-packages/rknnlite/api/rknn_lite.py", line 149, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 921, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

Init runtime environment failed

Process finished with exit code 255

**Comment by moyu026** [comment]
使用sudo运行就好了
