### ISSUE TITLE
E Calc node Conv : /model.0/conv/Conv output shape fail E Catch exception when loading onnx model: ./models/best.onnx!

### ISSUE THREAD

**Issue by lanssime** [rockchip-linux/rknn-toolkit#464]
最后几层报错了，前面可以
E Calc node Conv : /model.0/conv/Conv output shape fail
E Catch exception when loading onnx model: ./models/best.onnx!
E Traceback (most recent call last):
E   File "/home/zjh/anaconda3/envs/rknn1/lib/python3.8/site-packages/torch/fx/passes/utils/common.py", line 7, in <module>
E     from torch.fx.passes.utils.matcher_utils import SubgraphMatcher
E   File "/home/zjh/anaconda3/envs/rknn1/lib/python3.8/site-packages/torch/fx/passes/utils/matcher_utils.py", line 31, in <module>
E     logger = _init_logger()
E   File "/home/zjh/anaconda3/envs/rknn1/lib/python3.8/site-packages/torch/fx/passes/utils/matcher_utils.py", line 21, in _init_logger
E     logger.setLevel(level)
E   File "/home/zjh/anaconda3/envs/rknn1/lib/python3.8/logging/__init__.py", line 1421, in setLevel
E     self.level = _checkLevel(level)
E   File "/home/zjh/anaconda3/envs/rknn1/lib/python3.8/logging/__init__.py", line 198, in _checkLevel
E     raise ValueError("Unknown level: %r" % level)
E ValueError: Unknown level: 'WARNING'
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 115, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1161, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node Conv : /model.0/conv/Conv output shape fail
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by leshabirukov** [comment]
I got `E ValueError: Unknown level: 'WARNING'` just inside `import torchvision`, it was fixed by changing the order of imports. Personaly, I blame some dark magic with symbol context inside `rknn-lite`
