### ISSUE TITLE
支持多输入吗？输入的尺寸有些是二维 有些是三维 有些是四维

### ISSUE THREAD

**Issue by Gooddz1** [rockchip-linux/rknn-toolkit#474]
E RKNNAPI: Catch runtime Crash! Stack backtrace: 
Segmentation Fault
rknn_server() [0x40c160]
linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7f952505ac]
/lib64/libc.so.6(+0x82a88) [0x7f94ea2a88]
/usr/lib64/librknnrt.so(+0xb3418) [0x7f72c53418]
/usr/lib64/librknnrt.so(rknn_inputs_set+0x614) [0x7f72c65c64]
rknn_server() [0x409da0]
rknn_server() [0x40d1a8]
rknn_server() [0x40d6dc]
rknn_server() [0x406b5c]
/lib64/libc.so.6(+0x272e0) [0x7f94e472e0]
/lib64/libc.so.6(__libc_start_main+0xc4) [0x7f94e473dc]
rknn_server() [0x407050]

E RKNNAPI: rknn_outputs_get,  p_ctx->queue_output.size() = 0!
E inference: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2623, in rknn.api.rknn_base.RKNNBase.inference
  File "rknn/api/rknn_runtime.py", line 572, in rknn.api.rknn_runtime.RKNNRuntime.get_outputs
Exception: E Get outputs failed, error code: RKNN_ERR_FAIL

**Comment by Gooddz1** [comment]
> E RKNNAPI: Catch runtime Crash! Stack backtrace: Segmentation Fault rknn_server() [0x40c160] linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7f952505ac] /lib64/libc.so.6(+0x82a88) [0x7f94ea2a88] /usr/lib64/librknnrt.so(+0xb3418) [0x7f72c53418] /usr/lib64/librknnrt.so(rknn_inputs_set+0x614) [0x7f72c65c64] rknn_server() [0x409da0] rknn_server() [0x40d1a8] rknn_server() [0x40d6dc] rknn_server() [0x406b5c] /lib64/libc.so.6(+0x272e0) [0x7f94e472e0] /lib64/libc.so.6(__libc_start_main+0xc4) [0x7f94e473dc] rknn_server() [0x407050]
> 
> E RKNNAPI: rknn_outputs_get, p_ctx->queue_output.size() = 0! E inference: Traceback (most recent call last): File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper File "rknn/api/rknn_base.py", line 2623, in rknn.api.rknn_base.RKNNBase.inference File "rknn/api/rknn_runtime.py", line 572, in rknn.api.rknn_runtime.RKNNRuntime.get_outputs Exception: E Get outputs failed, error code: RKNN_ERR_FAIL

报了这个错误
