### ISSUE TITLE
Tensorflow Couldn't Convert Quantized Model to TFLite, convert with RKNN rules...

### ISSUE THREAD

**Issue by ifve** [rockchip-linux/rknn-toolkit#49]
当tensorflow框架下使用量化感知训练时，在原有模型上加入伪量化节点后转换rknn模型过程中会报错，应该怎么解决这个问题呢？
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 193, in rknn.api.rknn_base.RKNNBase.load_tensorflow
E   File "rknn/base/RKNNlib/RK_nn.py", line 47, in rknn.base.RKNNlib.RK_nn.RKnn.load_tensorflow
E   File "rknn/base/RKNNlib/app/importer/import_tensorflow.py", line 231, in rknn.base.RKNNlib.app.importer.import_tensorflow.Importensorflow.run
E ZeroDivisionError: float division by zero

**Comment by mahamatnoumai** [comment]
Any Chance u overcome this issues, and fix, am facing similar one too.
