### ISSUE TITLE
onnx转rknn失败

### ISSUE THREAD

**Issue by 1515292252** [rockchip-linux/rknn-toolkit#491]
文件夹中best.pt是源文件，v10-320-200-1122.onnx是best.pt转换成的，onnx_to_rknn.py是我自己写的转换脚本，log_feedback_to_the_rknn_toolkit_dev_team.log是运行onnx_to_rknn.py后生成的日志，报错如下：
W rknn-toolkit version: 1.7.5
--> Loading model
W base_optimize check ...
W "output0": cosine = 1.0, euclidean = 0.0
W correct_ops check ...
W "output0": cosine = 1.0, euclidean = 0.0
W fuse_ops check ...
W "output0": cosine = 1.0, euclidean = 0.0
E Calc node GatherElements : /model.23/GatherElements output shape fail
E Catch exception when loading onnx model: ./optimize.onnx!
E Traceback (most recent call last):
E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/gather_elements.py", line 19, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.gather_elements.GatherElements
E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/gather_elements.py", line 12, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.gather_elements.GatherElements.gather_elements
E File "<array_function internals>", line 5, in choose
E File "/home/tsh/anaconda3/envs/py38_rknn1.7.5/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 430, in choose
E return _wrapfunc(a, 'choose', choices, out=out, mode=mode)
E File "/home/tsh/anaconda3/envs/py38_rknn1.7.5/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
E return bound(*args, **kwds)
E ValueError: Need at least 0 and at most 32 array objects.
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 120, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 123, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.init
E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1187, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node GatherElements : /model.23/GatherElements output shape fail
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
load model failed
Exception ignored in: <function RKNN.del at 0x7f3ddf350820>
Traceback (most recent call last):
File "/home/tsh/anaconda3/envs/py38_rknn1.7.5/lib/python3.8/site-packages/rknn/api/rknn.py", line 781, in del
AttributeError: 'NoneType' object has no attribute 'FileHandler'
问GPT说是输出节点形状不对，要修改，但是也没说应该改成什么样子的呀。
这个在3588上是能跑的所以源文件应该不会有问题，但现在想部署在1126上，如何解决呢？
[log_feedback_to_the_rknn_toolkit_dev_team.log](https://github.com/user-attachments/files/18076041/log_feedback_to_the_rknn_toolkit_dev_team.log)

**Comment by frankyzc** [comment]
问题解决了吗

**Comment by 1515292252** [comment]
> 问题解决了吗
还没有  你也遇到这个问题了吗

**Comment by frankyzc** [comment]
对，加个微信？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1515292252 ***@***.***&gt;
发送时间: 2024年12月16日 15:11
收件人: rockchip-linux/rknn-toolkit ***@***.***&gt;
抄送: frankyzc ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rockchip-linux/rknn-toolkit] onnx转rknn失败 (Issue #491)





  
问题解决了吗
 还没有  你也遇到这个问题了吗

**Comment by 1515292252** [comment]
可以


tsh980612








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rockchip-linux/rknn-toolkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 凌晨4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rockchip-linux/rknn-toolkit] onnx转rknn失败 (Issue #491)





 对，加个微信？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 1515292252 ***@***.***&amp;gt; 
 发送时间: 2024年12月16日 15:11 
 收件人: rockchip-linux/rknn-toolkit ***@***.***&amp;gt; 
 抄送: frankyzc ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [rockchip-linux/rknn-toolkit] onnx转rknn失败 (Issue #491) 
 
 
 
 
 
    
 问题解决了吗 
  还没有  你也遇到这个问题了吗
