### ISSUE TITLE
onnx to rknn , error： 'NoneType' object has no attribute 'lid'

### ISSUE THREAD

**Issue by ljq19940913** [rockchip-linux/rknn-toolkit#50]
when i execute "rknn.load_onnx()" i got an error 

i train model and make onnx model in torch 1.2.0 ,and now i make rknn in a new environment which is rknn-toolkit 1.6.0 torch 1.5.1，is that something wrong? 

W Not get any connection of Dropout_717:out0
E Catch exception when loading onnx model: ./model/model.onnx!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 264, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 135, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 122, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 904, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.graph_connection_build
E AttributeError: 'NoneType' object has no attribute 'lid'
Load model failed!

**Comment by liuyiyiyiyi** [comment]
> when i execute "rknn.load_onnx()" i got an error
> 
> i train model and make onnx model in torch 1.2.0 ,and now i make rknn in a new environment which is rknn-toolkit 1.6.0 torch 1.5.1，is that something wrong?
> 
> W Not get any connection of Dropout_717:out0
> E Catch exception when loading onnx model: ./model/model.onnx!
> E Traceback (most recent call last):
> E File "rknn/api/rknn_base.py", line 264, in rknn.api.rknn_base.RKNNBase.load_onnx
> E File "rknn/base/RKNNlib/RK_nn.py", line 135, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
> E File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 122, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
> E File "rknn/base/RKNNlib/converter/convert_onnx.py", line 904, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.graph_connection_build
> E AttributeError: 'NoneType' object has no attribute 'lid'
> Load model failed!

have you sovled the problem?
