### ISSUE TITLE
rv1126 py3.7 rknn_toolkit_lite-1.6.0/examples/inference_with_lite librknn_api.so: undefined symbol: rknn_get_output_num

### ISSUE THREAD

**Issue by junhuanchen** [rockchip-linux/rknn-toolkit#53]
install rknn_toolkit_lite-1.6.0-cp36-cp36m-linux_armv7l.whl change to rknn_toolkit_lite-1.6.0-cp37-cp37m-linux_armv7l.whl

use rv1126(armv7l) python3.7 run rknn_toolkit_lite-1.6.0/rknn-toolkit-lite/examples/inference_with_lite raise librknn_api.so: undefined symbol: rknn_get_output_num

```bash
[root@RV1126_RV1109:/inference_with_lite]# python test.py 
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.api.rknn_platform_utils' does not match runtime version 3.7
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.api.rknn_model' does not match runtime version 3.7
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.api.rknn_log' does not match runtime version 3.7
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.api.rknn_utils' does not match runtime version 3.7
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.api.npu_config.cpu_npu_mapper' does not match runtime version 3.7
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.utils.yaml_parser' does not match runtime version 3.7
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.api.rknn_runtime' does not match runtime version 3.7
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'rknnlite.api.rknn_perf' does not match runtime version 3.7
--> Load RKNN model
done
--> Init runtime environment
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rknnlite/api/rknn_lite.py", line 140, in init_runtime
    async_mode=async_mode, rknn2precompile=rknn2precompile)
  File "rknnlite/api/rknn_runtime.py", line 162, in rknnlite.api.rknn_runtime.RKNNRuntime.__init__
  File "rknnlite/api/rknn_runtime.py", line 250, in rknnlite.api.rknn_runtime.RKNNRuntime._load_library
  File "/home/juwan/rv1126_project/buildroot/output/rockchip_rv1126_rv1109/target/usr/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
  File "/home/juwan/rv1126_project/buildroot/output/rockchip_rv1126_rv1109/target/usr/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
AttributeError: /usr/lib/python3.7/site-packages/rknnlite/api/lib/hardware/PUMA/linux-x86_64/librknn_api.so: undefined symbol: rknn_get_output_num

Init runtime environment failed
[root@RV1126_RV1109:/inference_with_lite]# 

```

librknn_api.so use 

- ./rv1126_project/external/rknpu/rknn/rknn_api/librknn_api/lib/librknn_api.so
- ./rknn-toolkit-v1.6.0/rknn-toolkit-lite/packages/rknn_toolkit_lite-1.6.0/rknnlite/api/lib/hardware/PUMA/linux-x86_64/librknn_api.so

**Comment by demonstan** [comment]
I got the same issue.

**Comment by CaoWGG** [comment]
@demonstan @junhuanchen 
求问如何在 rv1109 上装 rknnlite 包，可以分享一下相关编译好的包吗（psutil 和 numpy）？

**Comment by junhuanchen** [comment]
用 C 就好，不用浪费生命折腾 py ，或者看我家的 wiki.sipeed.com/maixpy3

**Comment by jiekechoo** [comment]
> 用 C 就好，不用浪费生命折腾 py ，或者看我家的 https://wiki.sipeed.com/maixpy3

虽说 C 版本很好，但是 python 版本调试和修改很方便。
