### ISSUE TITLE
The following operators are not implemented: ['aten::split_with_sizes']

### ISSUE THREAD

**Issue by zxzheng826** [rockchip-linux/rknn-toolkit#55]
Using rknn.load_pytorch(), found a operate not supported.
The model is trained in torch.__version__=1.6.0
`E Catch exception when loading pytorch model: ./nanodet_eff0.pt!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 339, in rknn.api.rknn_base.RKNNBase.load_pytorch
E   File "rknn/base/RKNNlib/RK_nn.py", line 146, in rknn.base.RKNNlib.RK_nn.RKnn.load_pytorch
E   File "rknn/base/RKNNlib/app/importer/import_pytorch.py", line 128, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2250, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2055, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.report_missing_conversion
E NotImplementedError: The following operators are not implemented: ['aten::split_with_sizes']`

**Comment by ymw123** [comment]
Did you successfully convert nanot?

**Comment by CaesarG** [comment]
Did you successfully convert nanot?
