### ISSUE TITLE
调用rknn.build()时设置do_quantization=True报错，datasets为10*320*320的数据

### ISSUE THREAD

**Issue by lndawn** [rockchip-linux/rknn-toolkit#74]
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 592, in rknn.api.rknn_base.RKNNBase.build
E   File "rknn/api/rknn_base.py", line 1490, in rknn.api.rknn_base.RKNNBase._quantize2
E   File "rknn/base/RKNNlib/RK_nn.py", line 553, in rknn.base.RKNNlib.RK_nn.RKnn.quantize
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 145, in rknn.base.RKNNlib.app.medusa.quantization.Quantization.run
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 43, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._run_quantization
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 112, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._quantize_net
E   File "rknn/base/RKNNlib/quantization/quantize_manager.py", line 352, in rknn.base.RKNNlib.quantization.quantize_manager.QuantizeManager.quantize
E   File "rknn/base/RKNNlib/quantization/quantize_manager.py", line 31, in rknn.base.RKNNlib.quantization.quantize_manager.QuantizerConfig.__init__
E AssertionError

**Comment by lswgh** [comment]
请问你解决了这个问题了吗,我也遇到相同的问题了
