### ISSUE TITLE
Can't run darknet example.

### ISSUE THREAD

**Issue by diazGT94** [rockchip-linux/rknn-toolkit#75]
Hello,

I'm trying to run the darknet example on the PC simulator using python 3.6 however when it tries to run the enviroment I get the following error:

--> Init runtime environment
E [vnn_CreateRKNN:5435]load_json:Error before: .0, 255.0, 255.0], "reorder": [0, 1, 2], "input_num": 1, "output_num": 3, "pre_compile": 0, "case_type": -1, "nodes": [{"lid": "convolution_0_1", "name": "convolution_0", "op": "RKNN_OP_CONV2D", "uid": 1, "input_num": 3, "output_num": 1, "nn": {"conv2d": {"ksize": [3, 3], "weights": 32, "stride": [1, 1], "pad": [1, 1, 1, 1], "group": 1, "dilation": [1, 1], "multiplier": 0}}, "vx": {"overflow_policy": "VX_CONVERT_POLICY_SATURATE", "rounding_policy": "VX_ROUND_POLICY_TO_ZERO", "down_scale_size_rounding": "VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR"}}, {"lid": "leakyrelu_0_3", "name": "leakyrelu_0", "op": "RKNN_OP_LEAKY_RELU", "uid": 3, "input_num": 1, "output_num": 1, "nn": {"activation": {"leaky_ratio": 0.1}}}, {"lid": "convolution_1_4", "name": "convolution_1", "op": "RKNN_OP_CONV2D", "uid": 4, "input_num": 3, "output_num": 1, "nn": {"conv2d": {"ksize": [3, 3], "weights": 64, "stride": [2, 2], "pad": [1, 1, 1, 1], "group": 1, "dilation": [1, 1], "mult
Create RKNN model fail, error=-6
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 859, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 340, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID
Init runtime environment failed.

I'm able to run other examples such as tflite and tensorflow. Any suggestions of how should I debug the error?

**Comment by diazGT94** [comment]
I was able to pass this issue by removing the following imports from the code
1) from matplotlib import gridspec
2) from matplotlib import pyplot as plt
