### ISSUE TITLE
onnx转rknn时lstm算子报错

### ISSUE THREAD

**Issue by Ajie16** [rockchip-linux/rknn-toolkit#78]
报错信息如下：
```
--> Config model

--> Loading onnx model
I Start importing onnx...
D ONNX model check failed, Exception: ValidationError("Field 'name' of graph is required to be non-empty.",)
W Call onnx.optimizer.optimize fail, skip optimize
I Current ONNX Model use ir_version 6 opset_version 9
D Calc tensor Initializer_629 (1, 512)
D Calc tensor Initializer_628 (1, 256, 64)
D Calc tensor Initializer_627 (1, 256, 3328)
D Calc tensor LSTM_464 (7, 1, 1, 64)
D Calc tensor LSTM_465 (1, 1, 64)
D Calc tensor LSTM_466 (1, 1, 64)
D import clients finished
I build output layer attach_LSTM_LSTM_131:out0
I build output layer attach_LSTM_LSTM_131:out1
I build output layer attach_LSTM_LSTM_131:out2
I Try match LSTM_LSTM_131:out2
W Not match tensor LSTM_LSTM_131:out2 
E Try match LSTM_LSTM_131:out2 failed, catch exception!
W ----------------Warning(2)----------------
E Catch exception when loading onnx model: D:\RK3399\test_onnx\test_lstm.onnx!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1152, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1054, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn\api\rknn_base.py", line 278, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn\base\RKNNlib\RK_nn.py", line 135, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn\base\RKNNlib\app\importer\import_onnx.py", line 121, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 1158, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn\api\rknn_log.py", line 312, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match LSTM_LSTM_131:out2 failed, catch exception!
--> Load onnx model failed!
```
看样子像缺少一些参数，请问Onnx中LSTM转Rknn有什么限制吗？

**Comment by Ajie16** [comment]
onnx是python生成的，Pytorch版本要对上

**Comment by 1079863482** [comment]
> onnx是python生成的，Pytorch版本要对上

请问下最后是怎么解决的？
