### ISSUE TITLE
onnx模型转rknn报GRU_46 output shape fail

### ISSUE THREAD

**Issue by yaphet266** [rockchip-linux/rknn-toolkit#96]
详细报错信息如下：
PS E:\soft\计算棒\rknn-toolkit-1.7.0\examples\onnx\words_demo> python test1.py
--> Config model
done
--> Loading model
W Call onnx.optimizer.optimize fail, skip optimize
E Calc node GRU : GRU_46 output shape fail
W ----------------Warning(1)----------------
E Catch exception when loading onnx model: crnn_word_rec.onnx!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\ops\gru.py", line 101, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.gru.GRU
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\ops\gru.py", line 45, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.gru.gru_helper.__init__
E NotImplementedError
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn\api\rknn_base.py", line 292, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn\base\RKNNlib\RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn\base\RKNNlib\app\importer\import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 94, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn\base\RKNNlib\converter\convert_onnx.py", line 984, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn\base\RKNNlib\onnx_ir\onnx_numpy_backend\shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn\api\rknn_log.py", line 312, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node GRU : GRU_46 output shape fail
Load crnn_word_rec failed!

模型结构地址：[https://github.com/yaphet266/rknn/blob/main/crnn_word_rec.png](url)

**Comment by eRaul** [comment]
GRU OP还不支持。后续版本会完善该OP的支持。
